// 破晓哥实战决策库 · 决策卡库（案例证据）
// ⚠️ 由 xiaolaoshi/tools/sync_knowledge.py 从工作区 m<N>/cards/cases.json 同步生成，勿手改
// 语料：faster-whisper medium 口播转录 + 关键帧画面佐证（原话已校正同音错字）
// 约定：理由保留原话；置信度 < 1 的牌张细节以口播为准；破晓哥锚点待理论对齐。

import type { DecisionCase } from './xiaoshiTypes'

/** 期数元信息（头条/抖音双平台同款分发；douyinId 为 null 表示未采集） */
export const SOURCE_EPISODES = {
  'cas-001': {
    episode: 1,
    title: '下家7筒打得好 暂时不要叫',
    douyinId: '7680778163680496906',
    toutiaoId: '7680861801106145844',
    durationSec: 286.79,
    transcriptPath: 'xiaolaoshi/m0/asr/transcript.json',
  },
  'cas-002': {
    episode: 2,
    title: '该怂就怂 不然挨个满的',
    douyinId: null,
    toutiaoId: '7678279057707893258',
    durationSec: 233,
    transcriptPath: 'xiaolaoshi/m1/asr/transcript.json',
  },
  'cas-003': {
    episode: 3,
    title: '根据期望 进攻思路',
    douyinId: null,
    toutiaoId: '7682347050817552942',
    durationSec: 288.5,
    transcriptPath: 'xiaolaoshi/m2/asr/transcript.json',
  },
  'cas-004': {
    episode: 4,
    title: '下家要打单钓我',
    douyinId: null,
    toutiaoId: '7681980310389293578',
    durationSec: 277.19,
    transcriptPath: 'xiaolaoshi/m3/asr/transcript.json',
  },
  'cas-005': {
    episode: 5,
    title: '两家收条 无奈占筒',
    douyinId: null,
    toutiaoId: '7681613925388911130',
    durationSec: 215.39,
    transcriptPath: 'xiaolaoshi/m4/asr/transcript.json',
  },
  'cas-006': {
    episode: 6,
    title: '对子多了 不一定好',
    douyinId: null,
    toutiaoId: '7681232706541191690',
    durationSec: 269.98,
    transcriptPath: 'xiaolaoshi/m5/asr/transcript.json',
  },
  'cas-007': {
    episode: 7,
    title: '面对大牌 逃跑思路',
    douyinId: null,
    toutiaoId: '7680494928945742370',
    durationSec: 288.78,
    transcriptPath: 'xiaolaoshi/m6/asr/transcript.json',
  },
  'cas-008': {
    episode: 8,
    title: '该跑就跑 见机行事',
    douyinId: null,
    toutiaoId: '7680127204625220148',
    durationSec: 163.69,
    transcriptPath: 'xiaolaoshi/m7/asr/transcript.json',
  },
  'cas-009': {
    episode: 9,
    title: '这牌给你打，你会做清吗',
    douyinId: null,
    toutiaoId: '7679752975199240731',
    durationSec: 238.47,
    transcriptPath: 'xiaolaoshi/m8/asr/transcript.json',
  },
  'cas-010': {
    episode: 10,
    title: '牌不上章 找叫思路',
    douyinId: null,
    toutiaoId: '7679380608237339155',
    durationSec: 164.66,
    transcriptPath: 'xiaolaoshi/m9/asr/transcript.json',
  },
  'cas-011': {
    episode: 11,
    title: '二筒碰早了 结果.......',
    douyinId: null,
    toutiaoId: '7679006465943831040',
    durationSec: 166.51,
    transcriptPath: 'xiaolaoshi/m10/asr/transcript.json',
  },
  'cas-012': {
    episode: 12,
    title: '估出4万很可能还在才这样打 进章效率最大该大8筒',
    douyinId: null,
    toutiaoId: '7678636799819776548',
    durationSec: 327.5,
    transcriptPath: 'xiaolaoshi/m11/asr/transcript.json',
  },
} as const

export const XIAOSHI_CASES: readonly DecisionCase[] = [
  {
    id: 'cas_001_d1',
    theme: '整局实战与复盘',
    timestamp: [95, 161],
    situation: {
      summary: '缺万余两门；已暗杠三筒；六条成对，可碰六条即下叫胡六九条；下家刚打四筒五筒七筒；桌面五筒现两张、七筒现一张',
      riverKey: [
        { tile: '4筒', by: '下家' },
        { tile: '5筒', by: '下家', note: '桌面共现两张' },
        { tile: '7筒', by: '下家' },
        { tile: '9条', by: '桌面' },
      ],
    },
    action: { type: 'decline_pong', detail: '不碰六条，保留靠六筒变叫（摸5筒胡47筒/摸4筒卡张5筒/摸7筒胡58筒）' },
    reasonQuotes: [
      '我的话不会要这张六条，因为上家九条已经碰了，六条也是中张，两边也并没有断张',
      '碰六条可能可以胡到九条，也有可能是死叫一直玩到最后',
      '暂时不要叫，是为了后面更好的叫。否则有可能下叫也是给自己看',
    ],
    boundary: '若下家打八筒，则碰，下三六九条叫（三条还很好）',
    outcome: '后续六筒自摸净收8分',
    confidence: 0.9,
    zhuyangAnchor: '下听宽度/存活率优先',
  },
  {
    id: 'cas_001_d2',
    theme: '整局实战与复盘',
    timestamp: [186, 219],
    situation: {
      summary: '摸进八筒（可杠）；表面可打六筒下三六九条叫；下家已打过七筒、九筒',
      riverKey: [
        { tile: '7筒', by: '下家' },
        { tile: '9筒', by: '下家' },
      ],
    },
    action: { type: 'discard', detail: '打六条，保筒子（待六七筒自摸），不追三六九条' },
    reasonQuotes: [
      '下家打过七筒九筒，现在我摸到了八筒，下家手上极大概率是没有高张筒子的',
      '八筒还可以杠。但如果下家手上有四五六筒或者五六七筒的话，八筒杠了六筒就胡不到了',
      '六七筒的自摸肯定比三六九条会来得容易',
    ],
    boundary: '推断依赖下家按常理打牌；对手骚操作型需降权',
    outcome: '六筒自摸净收8分',
    confidence: 0.85,
    zhuyangAnchor: '牌河辐射/进张效率',
  },
  {
    id: 'cas_001_d3',
    theme: '整局实战与复盘',
    timestamp: [242, 285],
    situation: {
      summary: '下家非常规：不碰一筒、弃对出改卡张八筒后又换对出一筒七筒并自摸；潇因反常行为高估七筒存活',
    },
    action: { type: 'observation', detail: '复盘对手偏离概率最优的行为对牌河推断的干扰' },
    reasonQuotes: [
      '不怕对手太厉害，只怕对手骚操作。乱拳可以打死老师傅',
      '如果不是下家这个非常规的打法，我也不会判断七筒非常的好，结果七筒在牌墙里只有一张',
    ],
    boundary: null,
    outcome: null,
    confidence: 0.7,
    zhuyangAnchor: '对手建模/置信度修正',
  },
  {
    id: 'cas_002_d1',
    theme: '对子搭子与牌效率',
    timestamp: [54, 114],
    situation: {
      summary: '前期；潇缺筒已打缺，下家缺条、对家上家缺万；碰三条后需在九万/一万/二条中弃一张；方向做三六万搭子叫或大单调；万字自己和下家都要',
      riverKey: [
        { tile: '2条', by: '上家', note: '上家打过二条→其手中应无二条' },
        { tile: '3条', by: '自己', note: '潇碰三条' },
      ],
    },
    action: { type: 'discard', detail: '碰三条后打一万，留九万（搭七万可上八万）与二条（等摸对）' },
    reasonQuotes: [
      '九万靠着七万，多一个上八万的机会肯定不会打',
      '一万是说不准是否能摸成对儿能碰到',
      '但是二条上家打过，现在三条碰了，上家手上应该是没有二条的',
      '哪一张多留一下就多一个成对儿的机会',
    ],
    boundary: '若有人以『抱肚子』拆搭方式打出的二条/三条，则二条存活推断反转；该可能性不高',
    outcome: '后续成三六万搭子叫；终局胡下家六万（见 cas_002_d2）',
    confidence: 0.85,
    zhuyangAnchor: '牌河存活推断/进张效率',
  },
  {
    id: 'cas_002_d2',
    theme: '防守与逃跑',
    timestamp: [157, 216],
    situation: {
      summary: '中后期；潇听三六万搭子叫，常规可对下家点三万『放一手』等自摸/升张；但上家已做成大单调单调二条（碰二筒前刚摸三条、大单调拆打三条），且二筒巴杠隐患明确：上家三筒断张、二筒必在牌墙，巴杠二筒后杠上自摸二条即满牌；上期(23号)同一上家险些二筒自摸满',
      riverKey: [
        { tile: '2条', by: '上家', note: '推测上家单调二条' },
        { tile: '3条', by: '上家', note: '上家大单调拆打三条' },
        { tile: '3筒', by: '桌面', note: '三筒断张→二筒在上家路径上' },
      ],
    },
    action: { type: 'hu', detail: '点炮即胡：三万也走、六万更要走；实际胡下家六万' },
    reasonQuotes: [
      '所以我这时候心里想的是，即使下家打出三万，我也会胡这个牌，当然如果打出六万就更要走了',
      '如果上家没有做成大单调、不是这个二筒的隐患，下家打三万我是会放的，但是这种局势没有必要再去谈了',
      '还好胡了，扯走了上家的二筒巴杠',
    ],
    boundary: '无满牌威胁时保留放一手等自摸的打法；威胁=对手大牌成势+杠上花路径，而非泛泛的『有人做大』',
    outcome: '胡六万进1分；反事实：不走则上家巴杠二筒杠起二条满牌三家共17分，且帮另两家节约9分',
    confidence: 0.85,
    zhuyangAnchor: '期望/风险权衡：止损与确定性收益优先',
  },
  {
    id: 'cas_002_d3',
    theme: '心态与理念',
    timestamp: [0, 16],
    situation: {
      summary: '本期开篇总纲与结尾总结（非单点决策）',
    },
    action: { type: 'observation', detail: '碰牌弃哪张、点炮走不走都提前想好 if-then 预案，随对手杠/做大动态调整；平时少喂下家' },
    reasonQuotes: [
      '打牌的时候，提前想好思路特别重要，也就是做好计划',
      '心中有方向，打牌就不慌',
      '当然也要根据别人是否杠牌是否做大来相应的调整',
      '总的来说，大家打牌的时候少放下家',
    ],
    boundary: null,
    outcome: '卡 cas_002_d2 即为『提前计划』的实例：点炮发生前已完成走/放切换',
    confidence: 0.7,
    zhuyangAnchor: '决策流程元认知',
  },
  {
    id: 'cas_011_d1',
    theme: '对子搭子与牌效率',
    timestamp: [14, 31],
    situation: {
      summary: '起手三对；对家打第一张二筒即碰，想往大单调走；碰后才得知下家也缺万，实际外面三家缺万',
    },
    action: { type: 'pong', detail: '早碰二筒（事后判定为亏：本可做万子清一色）' },
    reasonQuotes: [
      '碰牌之后才知道下家也缺万，结果外面三家缺万，这张二筒就碰亏了，不然这牌肯定是去做万清的',
      '不过极品（做大牌）的方式多种多样，除了清一色之外，大单调也是可以做满的',
    ],
    boundary: '早期（定缺刚结束、缺章信息未看全时）碰牌是不可逆决策，需先看全缺章再动手',
    outcome: '补救走大单调路线，终局胡单调九万（先3分再家家16分）',
    confidence: 0.9,
    zhuyangAnchor: '碰牌不可逆性/信息完备性',
  },
  {
    id: 'cas_011_d2',
    theme: '找叫与选叫',
    timestamp: [70, 135],
    situation: {
      summary: '碰一万后需在两种打法间选：打七万先不下叫（大单调最大化，理论吊张5→碰四万后更多）vs 打五万下叫优先（胡卡张八万，理论吊张4张：七万1+九万3）',
    },
    action: { type: 'discard', detail: '选下叫优先：打五万，胡卡张八万（差别只有一张，选早下叫）' },
    reasonQuotes: [
      '如果赌定要做大单调的话，这一手牌应该打七万先不要叫，这样九万还有三张、五万还有两张',
      '在碰出四万之前，外面有可能摸到你的吊张，那么胡张会减少；那么在碰四万之前，初始牌有五张可吊，那么等到碰出四万的时候，实际可以吊的胡张也会多一些',
      '还有一种就是打五万下叫优先，这样可以吊的胡张七万是一张、九万是三张，一共是四张',
      '由于差别只有一张，我还是选择了先打掉五万，胡卡张八万',
    ],
    boundary: '两者理论吊张差别大时应选吊张更多的路线；差别小（≤1张）时选早下叫（即时收益+防守价值）',
    outcome: '复盘：七万没了、下家打九万后『理论吊张目前只有两张了；如果当时打七万不要叫，理论吊张还有四张』——早下叫的代价被量化',
    confidence: 0.9,
    zhuyangAnchor: '下叫时机 vs 吊张宽度',
  },
  {
    id: 'cas_011_d3',
    theme: '期望与进攻',
    timestamp: [100, 111],
    situation: {
      summary: '胡卡张八万；对家与下家的牌看起来也不错',
    },
    action: { type: 'decline_hu', detail: '预设：摸到八万自摸（12分）就走；外面点炮八万则不胡' },
    reasonQuotes: [
      '如果摸到八万先自摸三家，收入十二分就胡了，因为对家和下家的牌看起来也不错',
      '但是如果外面八万点炮，我是不会胡的',
    ],
    boundary: '对手威胁大、自己还有自摸机会时成立；若牌局将尽或威胁已解除则应点炮即走',
    outcome: null,
    confidence: 0.85,
    zhuyangAnchor: '自摸溢价 vs 点炮折价',
  },
  {
    id: 'cas_011_d4',
    theme: '单钓七对与特殊牌型',
    timestamp: [0, 7],
    situation: {
      summary: '开篇缺章优势总纲 + 结尾大单调路线总结',
    },
    action: { type: 'observation', detail: '一家收牌且对子/叫多时，大单调比清一色更容易做满' },
    reasonQuotes: [
      '当自己想要的一个花色外面两家不要或者三家不要的时候，这种情况就属于缺章优势，比较适合制定进攻思路',
      '一家收牌的时候，如果对子、叫多，大单调做起来真的比清一色容易',
    ],
    boundary: null,
    outcome: '本局碰亏二筒后仍靠大单调拿下：胡单调九万，先进3分再进家家16分',
    confidence: 0.8,
    zhuyangAnchor: '大牌路线选择',
  },
  {
    id: 'cas_012_d1',
    theme: '对子搭子与牌效率',
    timestamp: [108, 126],
    situation: {
      summary: '烂牌期：半天不上牌；手上有死对与已失效的卡张搭子（卡张8万）',
    },
    action: { type: 'discard', detail: '不留5筒（留则下叫晚一步）；送出9万舍弃卡张8万，留2筒等8筒形成卡4筒搭子' },
    reasonQuotes: [
      '这张5筒没法留，留下的话下叫又会晚一步',
      '卡张8万已经没用了，9万只能送出去；2筒先留下，摸到8筒的话可以形成卡张4筒的搭子，总比卡张8万好',
    ],
    boundary: null,
    outcome: null,
    confidence: 0.85,
    zhuyangAnchor: '保留可转化搭子',
  },
  {
    id: 'cas_012_d2',
    theme: '找叫与选叫',
    timestamp: [134, 226],
    situation: {
      summary: '下家碰7筒、对家碰8筒；常规解是打8筒（安全且上6万/14筒/3万都可下叫）；他改打7万',
      riverKey: [
        { tile: '4筒', by: '下家', note: '下家刚打4筒，对家无反应' },
        { tile: '1万', by: '对家', note: '1万已杠断；对家此前打过1万' },
        { tile: '7万', by: '对家', note: '对家很早打过7万' },
      ],
    },
    action: { type: 'discard', detail: '打7万，改指望摸4万下叫（而非走14筒/6万路线）' },
    reasonQuotes: [
      '下家碰了7筒、对家碰了8筒，正常来说这一手打8筒是非常安全的，而且上6万、14筒、3万都可以下叫；但这一手牌我打的是7万',
      '首先筒子是4家要的牌，4筒和1筒肯定都很难上',
      '下家刚打了4筒，对家没有反应，对家应该是没有一对4筒的…总的来说这张4筒看似很好，但不必抱有指望了',
      '1筒是可能有一张，可能没有',
      '这个牌极有可能对家2万一坎…他已经碰了3筒8筒两副筒子，手上应该是万子居多，应该是一坎2万、一对3万',
      '如果是4、5万的话，对家就是1、3、6万的叫，之前他不会打1万出来',
      '所以这个牌虽然看着1、4筒还很多，但是靠1、4筒基本上没有指望，而指望4万下叫比6万下叫的可能性更高',
    ],
    boundary: '作者本人在结尾推翻了此决策（见 cas_012_d3）——复杂推断输给了更稳健的多路下叫路线',
    outcome: '随后摸到6万→杠收2分→杠起5万；终局摸到4万下叫（第107张），108张是5万',
    confidence: 0.9,
    zhuyangAnchor: '多路下叫 vs 单点深推断',
  },
  {
    id: 'cas_012_d3',
    theme: '心态与理念',
    timestamp: [295, 327],
    situation: {
      summary: '结果上成功下叫（摸4万），但作者复盘后自我推翻该决策',
    },
    action: { type: 'observation', detail: '复杂推断即使成立，也可能劣于更简单稳健的路线；应警惕『想太多』' },
    reasonQuotes: [
      '不过这一局的打法也是见仁见智吧',
      '我这样打是因为4万存在的机会会比6万机会更高；但是如果先摸到4万下叫，就必须把3万打出去',
      '所以总结起来，其实这样打也不是太对，这一局当时还是应该打8筒，不应该打7万',
      '我这算是想得太多，还是因为想得不够呢',
    ],
    boundary: '不等于『不要做深推断』，而是：当简单路线已具备多路下叫且不劣时，优先简单路线',
    outcome: '实战结果（摸到4万下叫）并未证明决策正确——作者仍判定当时该打8筒',
    confidence: 0.9,
    zhuyangAnchor: '奥卡姆/稳健优先原则',
  },
  {
    id: 'cas_012_d4',
    theme: '形势与信息',
    timestamp: [182, 219],
    situation: {
      summary: '1万已杠断、2万3万一张未现、4万被下家碰；对家已碰3筒与8筒两副筒子',
    },
    action: { type: 'observation', detail: '重建对家手牌：万子居多→一坎2万+一对3万；并用反事实排除4、5万组合' },
    reasonQuotes: [
      '他已经碰了3筒8筒两副筒子，手上应该是万子居多，应该是一坎2万、一对3万',
      '如果是4、5万的话，对家就是1、3、6万的叫，之前他不会打1万出来',
      '而5、6万比较有可能，因为他那张7万是很早打的，所以有可能4万、6万都在后面',
    ],
    boundary: null,
    outcome: '对家果然暗杠2万（结构与推断一致），付2分',
    confidence: 0.85,
    zhuyangAnchor: '副露+弃牌时序重建手牌',
  },
  {
    id: 'cas_012_d5',
    theme: '形势与信息',
    timestamp: [37, 41],
    situation: {
      summary: '上家碰了筒子后开始打条子',
    },
    action: { type: 'observation', detail: '副露方向+后续弃牌方向：碰筒后转打条→至少不会做清一色' },
    reasonQuotes: [
      '上家碰了筒子，开始打条，至少是不会做清一色了',
    ],
    boundary: null,
    outcome: null,
    confidence: 0.75,
    zhuyangAnchor: '清一色否定信号',
  },
  {
    id: 'cas_003_d1',
    theme: '期望与进攻',
    timestamp: [31, 107],
    situation: {
      summary: '潇缺筒，外面三家缺条（条子只有他一人在收=单行道），缺章处于优势；摸到八条后条子门内需取舍：打九条追下叫效率 vs 打幺鸡腾三条对子做牌',
      riverKey: [
        { tile: '7条', by: '桌面', note: '桌面已现两张+自己一张，七条基本无' },
        { tile: '1条', by: '桌面', note: '幺鸡已现两张' },
      ],
    },
    action: { type: 'discard', detail: '打掉幺鸡，舍弃二条进章，腾出三条对子去碰/摸成一坎做牌；不拆万子做清一色' },
    reasonQuotes: [
      '这一局我缺筒，外面三家缺条，缺章上处于优势，这种时候就适合制定进攻思路',
      '其实打九条，进牌下叫的效率是最高的；但如果是三家收条才会这样打，单行道是不会打九条的',
      '幺鸡桌面已经出现了两张，所以打掉幺鸡，舍弃掉二条的进章，把三条对子腾出来，来碰或者摸成一坎',
      '这牌就不要去拆万子做清一色了，肯定不划算',
    ],
    boundary: '多人争同一门（三家收条）→改打九条追下叫效率；单行道常规留幺鸡卡张二条。本局因幺鸡已现两张且想用三条做牌才例外',
    outcome: '二条随后瞬间出三张；他提醒『不过这个就是运气了』——结果好不等于决策对',
    confidence: 0.85,
    zhuyangAnchor: '缺章优势/进攻方向选择',
  },
  {
    id: 'cas_003_d2',
    theme: '找叫与选叫',
    timestamp: [107, 155],
    situation: {
      summary: '摸到三条后再弃一张定叫口：打八条胡四七条（四条出四张、七条剩一张，错）、打五条胡边七条（只有一张）、打九条胡对出五万八条；大单钓路线需拆七八九万，而本局四家都要万子',
      riverKey: [
        { tile: '4条', by: '桌面', note: '四条已出四张' },
        { tile: '7条', by: '桌面', note: '七条仅剩一张' },
      ],
    },
    action: { type: 'discard', detail: '打九条，胡对出（五万/八条），放弃大单钓路线' },
    reasonQuotes: [
      '胡四七条是肯定不对的——四条已经出了四张，七条也只有一张了',
      '打五条留下九条，九条有可能摸到后对，这种打法就是去做大单钓了',
      '但是这样打必定会拆出七八九万，而这一局四家都要万子…估计有人非常需要这两张牌来下叫',
      '如果要做大单钓，可能我还没做成，已经把肥羊都放跑了',
      '所以我选择不做大单钓，打掉九条胡对出，多一个五万，多一个杠上花的机会',
    ],
    boundary: '若万子无人争（非四家都要万），大单钓路线成立',
    outcome: '随后杠三条收4分，杠起六条',
    confidence: 0.85,
    zhuyangAnchor: '听牌宽度与喂牌代价',
  },
  {
    id: 'cas_003_d3',
    theme: '找叫与选叫',
    timestamp: [157, 200],
    situation: {
      summary: '杠三条后打五条换卡张七条；中途可碰六条改胡六九条（六条已无、九条还有两张），而原本胡五万八条仍可保留',
    },
    action: { type: 'other', detail: '改胡六九条：选存活张数最多的叫口（九条两张 > 八条一张）' },
    reasonQuotes: [
      '现在还有机会胡五万八条，担心这样打是没有坚持最初的叫，反而会错过金章自摸',
      '但九条多一张，肯定选九条',
      '九条多一张，永远选九条',
      '不过我一直是奉行长期主义，所以也没什么可懊恼的',
    ],
    boundary: '存活张数差距不大时（如 1 张 vs 1 张）此规则不适用，需转用进张效率/番型比较',
    outcome: '反例验证：改叫后转手错过八条自摸三家12分的机会；他仍坚持『长期下来就会有更好的进分结果』',
    confidence: 0.9,
    zhuyangAnchor: '听牌存活张数优先（结果无关原则）',
  },
  {
    id: 'cas_003_d4',
    theme: '期望与进攻',
    timestamp: [200, 282],
    situation: {
      summary: '尾盘；下家打出九条，他可胡（点炮约2分）；牌墙将尽，存在海底自摸机会；对家有约1/2概率跟打九条使他无法胡牌',
    },
    action: { type: 'decline_hu', detail: '不胡这张九条，放过赌海底自摸' },
    reasonQuotes: [
      '正确答案是这张九条肯定不该胡。这里用概率和期望来指导你的打法，就不该胡这张九条，长期下来就会有更好的收益',
      '对家有二分之一的机会跟一张九条，导致你无法胡牌，一分不进，失去了胡下家打的九条两分的机会',
      '放过这张九条，确实有二分之一的机会胡不到，但也有二分之一的机会摸海底…期望收益就是八分，高过胡这张九条的两分',
      '即使你们是打自摸加底，摸海底也有一加五分的机会，期望收益五分，也是高于胡这张九条两分的',
      '所以这张九条不用去胡，更何况说不定还有人没叫呢',
    ],
    boundary: '规则无海底/自摸加底加成、或点炮分值高（大牌）时结论反转；若已是最后一张必须胡则胡',
    outcome: '随后下一张真的是九条（错过），对家最终没叫；他『差对家四分，还划算一些』。若最后两张牌顺序调换（海底摸到九条）则本局进分20分',
    confidence: 0.9,
    zhuyangAnchor: '期望值最大化（EV 决策）',
  },
  {
    id: 'cas_003_d5',
    theme: '心态与理念',
    timestamp: [0, 25],
    situation: {
      summary: '开篇总纲与结尾方法论闭环（非单点决策）',
    },
    action: { type: 'observation', detail: '牌运不可控，但概率/机率可量化；用统计与概率提升长期结果，坚持长期主义' },
    reasonQuotes: [
      '牌运的好坏虽然是不可控的，但很多时候所谓的运气、机会、机率是可以被量化的',
      '将简单的统计和概率运用在麻将里面，是可以提升长期的结果的',
      '牌会扯来也会扯走，牌墙里的牌序不是我们可以控制的',
      '虽然这一局没有摸到海底九条，但是坚持期望收益是最大化的打法，长期下来就会有更好的进分结果',
    ],
    boundary: null,
    outcome: '卡 cas_003_d3/d4 为『结果打脸但决策正确』实例，构成本期方法论闭环',
    confidence: 0.7,
    zhuyangAnchor: '长期主义/方差与期望',
  },
  {
    id: 'cas_004_d1',
    theme: '形势与信息',
    timestamp: [98, 120],
    situation: {
      summary: '两家对两家：潇和下家缺条（只有这两家要万子），对家上家缺万；下家碰四筒做成大单调后打出一张8万',
      riverKey: [
        { tile: '5万', by: '下家', note: '下家此前打过5万' },
        { tile: '8万', by: '下家', note: '做大单调后打出，锁定其万子只剩一张' },
      ],
    },
    action: { type: 'observation', detail: '逆推下家手牌：只能收住一张万子，打8万→无非单钓6万/7万/9万；因打过5万→7万9万概率最高' },
    reasonQuotes: [
      '这一局只有我和下家要万，他手上只能收住一张万子，打8万，手上无非是掉6万、7万或者9万',
      '而他之前打过5万，所以掉7万和掉9万的机会是最高的',
      '所以现在他掉7、掉9万都是胡不到的，除非摸到6万，换成单调6万',
    ],
    boundary: '推断建立在『该门只有两家要』的缺章结构上；若多家争该门，收住张数不唯一，推断失效',
    outcome: '下家犹豫后打6万→『手上肯定是7万或9万中的一张』；终局证实其一直单钓7万',
    confidence: 0.9,
    zhuyangAnchor: '牌河+副露动作联合推断手牌结构',
  },
  {
    id: 'cas_004_d2',
    theme: '期望与进攻',
    timestamp: [119, 178],
    situation: {
      summary: '自己本可走素清/清七对/青龙七对路线；下家正做大单调且已暴露手牌范围（单钓6/7/9万）',
    },
    action: { type: 'pong', detail: '碰8万，放弃清七对/青龙七对，改做大对子走满牌路线反制' },
    reasonQuotes: [
      '这个牌8万肯定要去碰的，不能继续做清七对或者青龙七对',
      '否则待会他摸到6万，我们还得跟他抢牌，有机会让他跑掉',
      '碰了8万之后，4、7、9万必定还可以碰得到，2万也还可以杠，同样可以做成满牌，这样下家摸到6万也不敢轻易地换牌',
      '只要在他摸到6万之前，我们将4、7、9万任意再碰一对，这样他摸到6万敢换牌，就得点炮',
      '青龙七对虽然说起来很厉害…但是下叫是单调，就得和下家抢牌，失去优势',
      '手上都是活的对子的时候，做大对（大对子），就是对付他这种大单调最好的方法',
    ],
    boundary: '不因害怕下家而降番：『千万不要因为害怕下家去打4万，下对出7、9万的叫…打4万会少一番，不划算』',
    outcome: '下家最终被迫在7万/9万中打一张，『这就是杀人诛心啊』',
    confidence: 0.9,
    zhuyangAnchor: '满牌压制 + 降番代价评估',
  },
  {
    id: 'cas_004_d3',
    theme: '对子搭子与牌效率',
    timestamp: [155, 165],
    situation: {
      summary: '碰8万后需弃一张万子',
      riverKey: [
        { tile: '3万', by: '桌面', note: '3万桌面已现两张' },
      ],
    },
    action: { type: 'discard', detail: '打掉3万，留下5万' },
    reasonQuotes: [
      '3万桌面已经出现了两张，5万还有可能摸成对',
      '就先打掉3万，这样留下5万，如果我们摸到（5万），下家摸到掉5万，也就胡不到了',
    ],
    boundary: null,
    outcome: null,
    confidence: 0.85,
    zhuyangAnchor: '存活张 + 卡死对手叫口',
  },
  {
    id: 'cas_004_d4',
    theme: '心态与理念',
    timestamp: [0, 13],
    situation: {
      summary: '开篇信息总纲与结尾牌桌心态（非单点决策）',
    },
    action: { type: 'observation', detail: '两家收牌+一方给出明确信息≈单行道机会；得势不亮牌、不赶尽杀绝' },
    reasonQuotes: [
      '两家收牌的时候，如果另一方给出了比较明确的信息，那就基本上和单行道一样，有着较大的机会',
      '我也不会直接亮牌结束战斗，因为还有可能下家可以摸到1万或者筒子的巴杠。对于别人来说，一分两分也是分嘛',
      '牌好也不要太过的色（瑟），锋芒毕露，以免引起争议，闹得不愉快',
      '如果他（下家）不碰四筒、不做成大单调的话，6、9万早就胡了',
    ],
    boundary: null,
    outcome: '次级：前期打缺早晚是强弱信号；用缺章分布快速定位威胁来源（对家上家都在打条→威胁小）',
    confidence: 0.7,
    zhuyangAnchor: '信息价值 + 牌桌博弈伦理',
  },
  {
    id: 'cas_005_d0',
    theme: '找叫与选叫',
    timestamp: [0, 17],
    situation: {
      summary: '开篇公布潇式麻将法则第一条（总纲），结尾再给出边界修正；本局为其实证案例',
    },
    action: { type: 'observation', detail: '能变叫时把叫下到两家不要的门；但要按牌面尽力而为，不强行变叫' },
    reasonQuotes: [
      '两家不要就下这个叫…并把它称作潇式麻将法则第一条：如果能够变叫，尽量把叫朝着两家不要的方向去下',
      '但有时候变叫的过程，也需要冒一些相应的风险，如何权衡取舍',
      '所以『两家不要就下这个叫』，也要根据牌面尽力为之，而不是强行去下两家不要的叫，除非像前天的视频（暂时不要叫）之后，下叫也会非常容易',
    ],
    boundary: '强行变叫的前提：变叫成本低且变叫后胡张不薄。本局二条被杠断、五条已现两张、下家也收条 → 条子『两家不要』但胡张极薄 → 不强行变叫',
    outcome: '本局未拆对子，后续靠对家打出四筒收3分、九筒自摸各家4分',
    confidence: 0.9,
    zhuyangAnchor: '下听方向选择 + 变叫成本',
  },
  {
    id: 'cas_005_d1',
    theme: '对子搭子与牌效率',
    timestamp: [59, 78],
    situation: {
      summary: '我和下家缺万、对家上家缺条（两家不要条）；下家条子有点好；自己三四条在手，五条不好上',
    },
    action: { type: 'discard', detail: '先把三条打掉，保留五八条搭子方向' },
    reasonQuotes: [
      '因为五八条的搭子会比二五条更好',
      '如果三四条存着，待会三条被下家摸成了对，留久了反而成祸患',
      '因为这牌五条很不好上，很有可能需要靠上八条去下叫；而在摸到八条之前，如果外面再打掉一张五条，三四条就会非常被动',
    ],
    boundary: null,
    outcome: '随后还真摸到五条',
    confidence: 0.85,
    zhuyangAnchor: '搭子质量 + 未来风险张早弃',
  },
  {
    id: 'cas_005_d2',
    theme: '找叫与选叫',
    timestamp: [86, 97],
    situation: {
      summary: '摸到五条后，拆掉一九筒对子即可下叫胡二五八条；但二条被杠断、五条桌面已现两张、下家也在收条',
    },
    action: { type: 'decline_pong', detail: '不拆对子，保留一九筒继续等（放弃立即下叫）' },
    reasonQuotes: [
      '拆对子的话，这一手就下叫胡二五八条了，不过相当于胡五八条',
      '但之前也不好去拆一九筒，因为五条确实不好上',
    ],
    boundary: '若条子胡张不薄（二条未断、五条未现、下家不收条），则应拆对子变叫到两家不要的门',
    outcome: '复盘：若一开始拆对子则胡二五八条会先自摸；但两张五条都被自己摸到属小概率，不改决策',
    confidence: 0.85,
    zhuyangAnchor: '变叫成本 vs 胡张存活',
  },
  {
    id: 'cas_005_d3',
    theme: '形势与信息',
    timestamp: [125, 137],
    situation: {
      summary: '保留一九筒对子，需判断外面一四筒哪张会先出来',
    },
    action: { type: 'observation', detail: '判断一筒很深（不会出）、四筒反而可能出来 → 等四筒' },
    reasonQuotes: [
      '这个牌对于外面一四筒都是深张，一筒很深，反而四筒有可能会出来',
    ],
    boundary: null,
    outcome: '对家随后打出四筒，收3分',
    confidence: 0.85,
    zhuyangAnchor: '深张/浅张推断',
  },
  {
    id: 'cas_005_d4',
    theme: '形势与信息',
    timestamp: [173, 183],
    situation: {
      summary: '收官阶段观察对手弃牌行为（非单点决策）',
    },
    action: { type: 'observation', detail: '对手『不敢打某张』的犹豫本身就是信息，可反推其听牌结构' },
    reasonQuotes: [
      '下家最后是摸到九筒不敢打，打了八条；对家是单调一筒的大对，也就是说如果九筒被对家摸到，他才非常尴尬，打哪一张都要点我',
    ],
    boundary: null,
    outcome: null,
    confidence: 0.7,
    zhuyangAnchor: '对手建模/行为信息',
  },
  {
    id: 'cas_006_d1',
    theme: '对子搭子与牌效率',
    timestamp: [0, 14],
    situation: {
      summary: '开篇总纲（不做七对时对子多是负担）',
    },
    action: { type: 'observation', detail: '不做七对时不留多余对子；为尽早下叫、躲大牌，该拆就拆' },
    reasonQuotes: [
      '麻将新手和初级牌手都非常喜欢留对子，但在不做七对的时候，对子多了并不是一件好事',
      '有时候为了能够尽早下叫、躲过外面的大牌，对子多了还得拆掉',
    ],
    boundary: '做七对/龙七对路线时不适用',
    outcome: null,
    confidence: 0.8,
    zhuyangAnchor: '对子的机会成本',
  },
  {
    id: 'cas_006_d2',
    theme: '对子搭子与牌效率',
    timestamp: [108, 127],
    situation: {
      summary: '摸到七条；五条/七条取舍，卡张四条与卡张八条都未出现；桌面高张很深',
    },
    action: { type: 'discard', detail: '打掉七条，保留五条方向等四条下叫；顺便有望骗出九条' },
    reasonQuotes: [
      '留下五条摸四条可以下叫，留下七条摸八条可以下叫',
      '但桌面上的高张非常的深，估计七八九条都不太好出，所以不太指望去上八条',
      '打掉七条，说不定还可以把九条骗出来',
    ],
    boundary: null,
    outcome: '随后上家打出八条、对家无反应（成为后续推断的信息源）',
    confidence: 0.85,
    zhuyangAnchor: '深张方向的进张折价',
  },
  {
    id: 'cas_006_d3',
    theme: '对子搭子与牌效率',
    timestamp: [142, 197],
    situation: {
      summary: '手上四对：八万、三条、五条、九条，必须拆一对；大众直觉是打已现一张、最安全的五条',
      riverKey: [
        { tile: '5条', by: '桌面', note: '已现一张，打五条安全' },
        { tile: '8条', by: '上家', note: '上家打八条、对家无反应→高张已结构' },
      ],
    },
    action: { type: 'discard', detail: '拆九条对（打九条），保留五条对等其被打出' },
    reasonQuotes: [
      '这个牌八万是肯定不能拆的，因为六万九万已经打断，八万极大概率是可以碰到下叫的；如果先碰到了条子，胡八万也会比较稳妥',
      '相信很多人这手会继续打五条，因为桌面上已经出现了一张五条，打五条非常安全',
      '在我打了七条、上家打了八条、对家没有反应之后，我就知道高张条子非常容易成了两副顺子',
      '如果七八九条都在对家手上，有可能对家是在做七对，同时顺便做清一色',
      '五条如果对家做七对，他是摸不上来的，早晚会打掉',
      '九条这种生张的边张，是最容易崩对的，相对来说三条碰出的机会都会比九条更高',
      '所以这个牌虽然九条看着最危险、一张没出，但其实打九条才是最正确的',
    ],
    boundary: '若对家并非七对路线（五条不会被打出），则保留五条对的价值下降，需重估',
    outcome: '九条打出去无人碰；对家随后打出五条（成功躲过）；终局对家是青龙七对（66778899条）——『这一对九条我拆的真的是太正确了』',
    confidence: 0.9,
    zhuyangAnchor: '拆对判据：碰出概率 + 对手路线 + 安全≠正确',
  },
  {
    id: 'cas_006_d4',
    theme: '形势与信息',
    timestamp: [164, 180],
    situation: {
      summary: '对家在做条子清一色（连续打万子），但上家打出八条时对家没有反应',
    },
    action: { type: 'observation', detail: '『不碰=信息』：对手对某张无反应→该门高张已成结构，并据此推断其可能做七对+清一色' },
    reasonQuotes: [
      '在我打了七条、上家打了八条、对家没有反应之后，我就知道高张条子非常容易成了两副顺子，也就是说外面很容易有七八九、七八九或者六七八七八九',
      '如果七八九条都在对家手上，有可能对家是在做七对，同时顺便做清一色',
    ],
    boundary: null,
    outcome: '终局证实对家为青龙七对 66778899条',
    confidence: 0.85,
    zhuyangAnchor: '无反应信息/对手路线识别',
  },
  {
    id: 'cas_006_d5',
    theme: '心态与理念',
    timestamp: [230, 269],
    situation: {
      summary: '收官复盘（非单点决策）',
    },
    action: { type: 'observation', detail: '规避的是期望损失最大的威胁，结果被别家胡走不改决策正确性' },
    reasonQuotes: [
      '算是成功躲掉了对家的条子，不过还是没有躲过下家，真是躲得过初一躲不过十五啊',
      '虽然没能躲过下家的牌，但他其实只有一张胡张，我还多一张',
    ],
    boundary: null,
    outcome: '负下家10分，但避开了对家青龙七对（损失更大）',
    confidence: 0.7,
    zhuyangAnchor: '结果无关原则/期望损失最小化',
  },
  {
    id: 'cas_007_d1',
    theme: '心态与理念',
    timestamp: [0, 18],
    situation: {
      summary: '开篇总纲（躲大牌 vs 做大牌的频次账）',
    },
    action: { type: 'observation', detail: '躲大牌比做大牌重要：自己做大牌的机会是1次/若干局，别人做大牌要躲的机会是3次' },
    reasonQuotes: [
      '打川麻血战，学会躲大牌比做大牌更加重要',
      '因为长期来说大家的运气都差不多，平均下来你每做一个大牌，外面三家也各会做一个大牌',
      '所以做的那一次机会要尽量的做好，恰到好处的去贪分；而另外三家做的时候就要学会防御逃跑',
    ],
    boundary: null,
    outcome: null,
    confidence: 0.85,
    zhuyangAnchor: '期望损失频次/防守价值',
  },
  {
    id: 'cas_007_d2',
    theme: '防守与逃跑',
    timestamp: [134, 172],
    situation: {
      summary: '对家连续打万子+杠三筒→明显做筒子清一色；自己原听卡张三条（桌面已现两张三条，很可能无张）',
      riverKey: [
        { tile: '3条', by: '对家', note: '桌面已现两张，胡三条很可能没张' },
        { tile: '3筒', by: '对家', note: '对家杠三筒→筒子清一色路线' },
      ],
    },
    action: { type: 'discard', detail: '打二条，把叫从条子换成万子对出（六万/四条），借机靠五万七万转宽叫' },
    reasonQuotes: [
      '桌面上已经出现了两张三条，胡三条很可能一张都没有了',
      '因为对家做清一色，从不要条子变成条子、万子都不要，那么原本的缺张弱势，就变成了两家不要万，万子就只有我和下家要',
      '先换成对出的目的不是为了去胡六万，而是要去靠五万或者七万胡宽叫；摸到五万去胡一四七万，摸到七万去胡五八万，摸到一万去胡卡张五万',
    ],
    boundary: '对手若不走清一色（继续收该门），缺章格局不会反转，此路不成立',
    outcome: '后续成功躲掉对家清一色（『恭喜自己，逃跑成功』）',
    confidence: 0.9,
    zhuyangAnchor: '缺章结构反转/换叫逃生',
  },
  {
    id: 'cas_007_d3',
    theme: '形势与信息',
    timestamp: [186, 263],
    situation: {
      summary: '摸到七万后可换胡五八万，也可继续靠六万；下家胡牌早且一张万子未打过，无法精确读牌',
      riverKey: [
        { tile: '6万', by: '桌面', note: '六万桌上一张未现' },
      ],
    },
    action: { type: 'other', detail: '枚举下家万子牌型五种情形，逐一算张数后加总：五八万≈4-5张 > 六万≈2-3张 → 选五八万' },
    reasonQuotes: [
      '如果下家手上有一对六万，那么顺子应该有七八九万，然后有一二三、二三四或三四五万中的一副，而绝对不可能是两副',
      '各种情形之下的张数加起来，五八万会有四到五张，而六万会有两到三张',
      '下家胡牌太早，而且一张万子没有打过，什么情形都有可能，无法算出下家准确的手牌，只能用概率来辅助自己，做出最大可能性的选择',
    ],
    boundary: '能精确读到对手手牌时直接用精确解；本方法是『读不准』时的降级策略',
    outcome: '逃跑成功；结果上五八万与六万都只剩一张——再次印证结果打脸不改决策',
    confidence: 0.9,
    zhuyangAnchor: '情形枚举 + 期望存活张数',
  },
  {
    id: 'cas_007_d4',
    theme: '找叫与选叫',
    timestamp: [50, 63],
    situation: {
      summary: '五条出现，可碰；碰后可从两张上听变一张上听',
    },
    action: { type: 'pong', detail: '五条必碰（碰后下叫胡卡张三条）' },
    reasonQuotes: [
      '这个五条和前天的六万相似，一定要碰，这样可以从两张上听变成一张上听',
    ],
    boundary: null,
    outcome: '碰后下叫胡卡张三条；随后下家、上家先后自摸（各负2分）',
    confidence: 0.85,
    zhuyangAnchor: '上听张数压缩',
  },
  {
    id: 'cas_008_d1',
    theme: '心态与理念',
    timestamp: [0, 10],
    situation: {
      summary: '开篇总纲：中前期定路线与底线',
    },
    action: { type: 'observation', detail: '中前期看清形势，定好进攻/防御/逃跑思路，提前设定底线并坚定执行' },
    reasonQuotes: [
      '每一局的中前期一定要看清场上的形势，制定好进攻、防御或是逃跑的思路',
      '要提前想好自己的底线和原则，然后坚定的执行',
    ],
    boundary: null,
    outcome: null,
    confidence: 0.8,
    zhuyangAnchor: '决策预案/元认知',
  },
  {
    id: 'cas_008_d2',
    theme: '形势与信息',
    timestamp: [38, 115],
    situation: {
      summary: '我缺条、下家缺万、对家上家缺筒（缺张优势）；对家打筒打缺后连续打万，下家连续打一筒八筒二筒；上家一直打条子',
      riverKey: [
        { tile: '1筒', by: '下家' },
        { tile: '8筒', by: '下家' },
        { tile: '2筒', by: '下家' },
      ],
    },
    action: { type: 'other', detail: '识别对家做条子清一色、上家做万清；自己放弃拼筒子清一色' },
    reasonQuotes: [
      '对家打一张筒子就打缺了，然后连续打万，这种时候我们要提防对家做条子清一色',
      '对家这个是很明显了，做条子清一色；而上家也一直在打条子，有可能是想做万清',
      '对家手上已经全部都是条子了，这种情况上家还要打条，很明显上家是在做万清',
      '我就不去拼筒子清一色了，除非我能先摸到二筒，这种几率太小',
    ],
    boundary: '若自己极早摸到关键张（先摸到二筒），仍可拼清一色',
    outcome: null,
    confidence: 0.85,
    zhuyangAnchor: '清一色路线识别',
  },
  {
    id: 'cas_008_d3',
    theme: '防守与逃跑',
    timestamp: [114, 140],
    situation: {
      summary: '自己听六九筒；对家条子清一色已成型；需预设『哪些点炮必胡、哪些可放一手』',
    },
    action: { type: 'decline_hu', detail: '预设底线：九筒点炮必胡；六筒若点出且下家无反应→顺放一手' },
    reasonQuotes: [
      '现在这牌九筒点炮就胡，六筒看情况',
      '上家打九筒，我肯定要胡了',
      '但如果上家打的是六筒、下家没有反应，即便对家条清已经做成了，我这个牌也会顺放一手',
      '一个是对家不一定现在有叫；还有就是如果上家打六筒、下家没反应，六筒估计至少还有两张',
      '而我这个牌一筒三筒还可以摸巴杠，也是有机会做成大牌、胡在前面的；而且估计上家也没叫',
    ],
    boundary: '与 cas_002_d2 互补：对手存在满牌/杠上花紧迫威胁时→点炮就走（该怂就怂）；无紧迫威胁且张数充足、自己还有做大机会时→可放一手',
    outcome: '实战中上家打九筒即胡；后续对家打一筒后接着是六筒',
    confidence: 0.9,
    zhuyangAnchor: '点炮走牌 vs 放一手的条件化决策',
  },
  {
    id: 'cas_008_d4',
    theme: '形势与信息',
    timestamp: [153, 162],
    situation: {
      summary: '收官复盘：上家对潇的路线产生误判（非单点决策）',
    },
    action: { type: 'observation', detail: '自己的弃牌序列也是对手的信息源；对手误判会自己付出代价' },
    reasonQuotes: [
      '上家以为我在做筒子清一色，以为二三四万肯定在后面，到了后期才发现没有了，导致最后没叫，给对家赔一个满牌',
    ],
    boundary: null,
    outcome: null,
    confidence: 0.7,
    zhuyangAnchor: '信息不对称/对手建模',
  },
  {
    id: 'cas_009_d1',
    theme: '期望与进攻',
    timestamp: [110, 170],
    situation: {
      summary: '我缺筒、上家缺万、对家下家缺条；一度想做条子清一色，但七条已打绝、幺鸡绝在自己手上、六条被下家打出',
      riverKey: [
        { tile: '7条', by: '桌面', note: '七条已现三张/打绝' },
        { tile: '6条', by: '下家', note: '六条再出，七八条与四五条都不够用' },
      ],
    },
    action: { type: 'kang', detail: '放弃清一色，把摸到的一条（幺鸡）直接杠掉' },
    reasonQuotes: [
      '七条已经没了',
      '因为四五条也需要一张六条，所以这个牌清一色基本上已经没有希望了，除非一三六七条全部都被我摸到',
      '而幺鸡已经绝在我们自己手上，七条已经打绝',
      '这个牌做清一色，做出来就是给大家看的，除非外面有人没叫，不过看起来也不太像',
      '所以这张一条还是直接杠掉比较好；视频是暂停给大家讲解，实战的时候这张一条基本没有考虑',
    ],
    boundary: '若关键张（一三六七条）多数仍存活、且外面确实有人没叫，清一色路线可成立',
    outcome: '随后六条自摸两家收8分；下家二条自摸时『我的三六条都还有两张』',
    confidence: 0.9,
    zhuyangAnchor: '大牌可行性核算/存活张',
  },
  {
    id: 'cas_009_d2',
    theme: '形势与信息',
    timestamp: [140, 158],
    situation: {
      summary: '评估『留下幺鸡打四万、后续摸三六条再胡一四条/一四七条』这条路线的未来叫口质量',
    },
    action: { type: 'observation', detail: '预判未来叫：上家顺子结构（二三四/三四五/四五六条）吃掉四条 → 未来的叫是死叫 → 排除该路线' },
    reasonQuotes: [
      '因为上家手上很容易有二三四、三四五或者四五六条的顺子',
      '而这个牌留下幺鸡、打四万，即使后面摸到三六条，胡一四条、一四七条都是死叫',
      '因为上家顺子的情况不管哪一种，四条都是没有的',
    ],
    boundary: null,
    outcome: null,
    confidence: 0.85,
    zhuyangAnchor: '未来叫口存活预判',
  },
  {
    id: 'cas_009_d3',
    theme: '期望与进攻',
    timestamp: [219, 238],
    situation: {
      summary: '结果复盘：若坚持做清，后续可摸三条胡六条甚至海底满牌',
    },
    action: { type: 'observation', detail: '结果打脸不改打法：按期望收益决策，不按单局结果追认' },
    reasonQuotes: [
      '所以从结果上来说，如果我继续做清，摸到三条，胡六条还可以胡海底满牌',
      '但是打法上来说，我永远不会这样打',
      '因为算上我摸的六条，这三张三六条，前两张任意被他们摸一张就完蛋',
      '所以我常说打牌一定要有期望收益意识，这一点非常重要',
    ],
    boundary: null,
    outcome: null,
    confidence: 0.9,
    zhuyangAnchor: '期望收益意识/结果无关原则',
  },
  {
    id: 'cas_009_d4',
    theme: '心态与理念',
    timestamp: [175, 195],
    situation: {
      summary: '打六万前的节奏处理（非单点决策）',
    },
    action: { type: 'observation', detail: '用『假装犹豫』误导对手对自己听牌门的判断；但表演要自然，拙劣表演反而暴露' },
    reasonQuotes: [
      '这张六万是肯定要打的，不过假装考虑一下，让别人以为我在犹豫打万子，在听万子叫',
      '无声的演技还是很重要的，不过有些拙劣的表演就没必要',
    ],
    boundary: null,
    outcome: null,
    confidence: 0.7,
    zhuyangAnchor: '信息博弈/节奏控制',
  },
  {
    id: 'cas_010_d1',
    theme: '找叫与选叫',
    timestamp: [0, 13],
    situation: {
      summary: '开篇总纲：打不缺、不上牌时的取舍原则',
    },
    action: { type: 'observation', detail: '注意单牌与搭子的取舍，尽量提高下叫机会，同时兼顾防守不喂大别人' },
    reasonQuotes: [
      '打不缺、不上牌，这是所有玩四川麻将的人都可能遇到的问题',
      '这种时候我们一定要注意好对单牌和搭子的取舍，尽量的提高下叫的机会，同时也做好防守，不要让别人的牌轻易坐大',
    ],
    boundary: null,
    outcome: null,
    confidence: 0.8,
    zhuyangAnchor: '下叫概率 vs 放铳风险',
  },
  {
    id: 'cas_010_d2',
    theme: '对子搭子与牌效率',
    timestamp: [27, 42],
    situation: {
      summary: '上家缺条、我缺筒、对家下家缺万（两家不要万）；碰6万后需弃一张',
    },
    action: { type: 'discard', detail: '不按纯进张效率打1万，改打一条（幺鸡），赌摸到1万成后对可碰' },
    reasonQuotes: [
      '碰6万，进张效率最大化的话是打1万，但是这张牌我打了一条，因为觉得如果摸到1万这个后对应该能碰',
    ],
    boundary: '纯效率口径支持打1万；本选择是对『可碰性』的加权判断，属于可争议决策',
    outcome: '随后3万瞬间被打掉三张，『如果摸不到1、2万这牌估计有点艰难』——判断落空，如实复盘',
    confidence: 0.85,
    zhuyangAnchor: '进张效率 vs 碰出机会',
  },
  {
    id: 'cas_010_d3',
    theme: '防守与逃跑',
    timestamp: [82, 95],
    situation: {
      summary: '摸到8万；4万已被上家碰过、5万已杠断',
      riverKey: [
        { tile: '4万', by: '上家', note: '上家已碰过4万' },
      ],
    },
    action: { type: 'discard', detail: '先打4万，留8万（8万可摸成对，配合7条碰出仍可下叫）' },
    reasonQuotes: [
      '摸到8万一定要先打4万，上家已经碰过4万，早打早安全',
      '而且5万已经杠断，4万对于我们下叫没有任何帮助',
      '但是8万留下有可能摸成一对，然后7条碰出来还是可以下叫',
    ],
    boundary: null,
    outcome: '后续两家都摸不到8万，被对家摸走，8万最终没用上（结果打脸）',
    confidence: 0.9,
    zhuyangAnchor: '安全+无用+潜在价值三重判据',
  },
  {
    id: 'cas_010_d4',
    theme: '形势与信息',
    timestamp: [126, 164],
    situation: {
      summary: '上家碰9万后打7万；1万未断张、2万最后也没断，需判断3万是否还在牌墙',
      riverKey: [
        { tile: '2万', by: '上家', note: '上家在碰4万之前打过一张2万' },
        { tile: '9万', by: '上家', note: '上家碰9万后打7万' },
      ],
    },
    action: { type: 'observation', detail: '反事实推断：若上家真有123万，他不会先打2万（而应做清一色金3万胡2万）→ 3万仍在墙内' },
    reasonQuotes: [
      '为什么刚才上家碰9万、打7万，我就说8万和3万肯定还在呢',
      '8万是因为7万、9万断张，肯定还在，除非上家单钓',
      '因为上家在碰4万之前打过一张2万。如果上家手上有1、2、3万，他完全没必要打2万，而是应该做清一色，最后金3万在手上稳稳当当地胡2万',
      '所以说两家收牌的时候，观察另一家打过的牌非常关键',
    ],
    boundary: '依赖对手按合理路线打牌；对手非常规时推断降权',
    outcome: '『虽然1、2万没有断张看不出来，但也知道3万肯定还在牌墙后面』',
    confidence: 0.9,
    zhuyangAnchor: '反事实推断/牌河时序信息',
  },
  {
    id: 'cas_010_d5',
    theme: '对子搭子与牌效率',
    timestamp: [112, 126],
    situation: {
      summary: '手上3条、1万已成死对；边3万的叫已成形但3万被打绝',
    },
    action: { type: 'discard', detail: '死对先打掉1万；边3万叫被打绝后改下4条叫' },
    reasonQuotes: [
      '3条、1万都是死对，先打掉1万',
      '现在可以下边3万的叫，但已经被打绝了；然后对家打了4条，我这才下4条的叫，还好啊，赶上了最后一张',
    ],
    boundary: null,
    outcome: '赶上最后一张4条下叫',
    confidence: 0.85,
    zhuyangAnchor: '死张处理 + 换叫机动',
  },
] as const

/** 按决策卡 id 精确查找 */
export function getXiaoshiCase(id: string): DecisionCase | undefined {
  return XIAOSHI_CASES.find(c => c.id === id)
}

/** 按主题筛选决策卡 */
export function getXiaoshiCasesByTheme(theme: DecisionCase['theme']): readonly DecisionCase[] {
  return XIAOSHI_CASES.filter(c => c.theme === theme)
}
