/**
 * 潇老师主题地图 v1 —— 课程库数据（程序化生成，勿手改）
 *
 * 来源：今日头条主页全量抓取 309 条 → 去重 289 → 教学可用 260 条
 * 生成脚本对齐工作区《主题地图-v1-课表.md》；再生成时改 工作区/主题地图/ 数据后重跑转换。
 * 注意：titles 里的标题保留了 feed 清洗口径（无空格无中文标点）；
 * mustRead 用归一化（去空格/标点）模糊匹配，与人工课表标题对得上。
 * 用途：学习路径 UI / 导师总纲 / "期数→主题簇"反查 的数据源。
 */

/** 主题簇代码：教学 8 簇 + X（生活互动，不入课表） */
export type ClusterCode = 'E' | 'D' | 'I' | 'P' | 'T' | 'S' | 'G' | 'M' | 'X'

export interface XioshiClusterMeta {
  code: ClusterCode
  name: string
  summary: string
  /** 该簇全部期数标题（已去重、剔除话题标签） */
  titles: string[]
  /** 建议精读的期数标题（归一化匹配口径的子集） */
  mustRead: string[]
}

export interface PathLayer {
  id: string
  name: string
  /** 建议学习节奏 */
  weeks: string
  goal: string
  clusters: ClusterCode[]
}

export interface XioshiLesson {
  title: string
  cluster: ClusterCode
  /** 建议精读 */
  mustRead: boolean
  layerId: string | null
}

/** 归一化标题：去空格与常见中文标点（与 feed 清洗口径一致，供模糊匹配） */
export function normalizeTitle(s: string): string {
  return s.replace(/[，。！？、…—\s·]+/g, '')
}

/** 8 大教学簇 + 生活互动簇（v1 抓取于 2026-09-07） */
export const xiaoshiClusters: readonly XioshiClusterMeta[] = [
  {
    code: 'E',
    name: '期望与进攻',
    summary: '该贪就贪，但按期望收益贪',
    titles: [
      '根据期望进攻思路',
      '这牌给你打你会做清吗',
      '按期望收益还是可以做清',
      '稍微进攻意外之喜',
      '适度把握小机会',
      '见炮就跑使劲贪都不好',
      '优势进攻做大思路',
      '常理推断不做大对',
      '起手优势贪牌思路',
      '进攻思路',
      '适当做清两局连播',
      '处理好日常小牌的小贪和逃跑很重要',
      '缺牌优势按番种性价比来尽早自摸才对',
      '不该贪的时候绝对不会贪',
      '步步做大',
      '贪一下咋了',
      '进攻还是防守灵活思路',
      '小牌不贪策略尽力',
      '对手做清逃跑思路',
      '三家不要进攻思路',
      '小贪思路',
      '雨分可贵自摸价更高',
      '两家收牌小贪一下',
      '钓牌找思路加上概率期望指导抉择',
      '有机会想进攻但是防守也要算好',
      '带杠自摸YYDS',
      '三家不要',
      '寻找机会',
      '同行走了把握机会',
      '别人做清有风险也有机会',
      '该贪就该',
      '堵34条概率更大',
      '两家不要做清找叫',
      '贪清思路',
      '自摸技巧',
      '做清路上有取有舍',
      '两家收做清思路',
      '没有风险顺便进攻',
      '做清一色顺势而为',
      '去做清吧做不被定义的清一色',
      '评估机会和风险',
      '有时候只有一张了也要贪有时候还有两三张也要跑',
      '这牌你会做清吗#麻将教学',
      '用期望量化进牌效率#麻将教学',
      '这牌贪不下去了',
      '这牌该贪吗',
      '期望收益权衡取舍',
      '川麻里性价比最高的就是自摸',
      '双方博弈',
      '做清路上的进退把握',
      '做清进退',
      '牌局变化逃跑变进攻',
      '早叫想贪但也要合适些',
      '虽有性价比',
      '缺章弱势手牌优势',
      '对手做清灵活防守#麻将技术',
      '贪攻的时候尽量回避风险',
      '识别机会该贪就贪',
      '碰牌换叫提升胡牌概率',
      '进攻思路略有不同寻常',
      '缺章变化进攻思路',
      '这个卡章必贪',
      '概率问题',
      '进攻思路把握优势',
      '根据局势制定进攻策略',
      '牌局进程选择贪到极致',
      '三家收做清选叫思路',
      '自摸多多',
      '做不做清进退有度',
      '缺章弱势分析牌局制定进攻',
      '该放就放机会是自己把握的',
      '高手都知道的细节海底是机会',
      '真的是最不爱做清一色的麻将博主',
      '以小博大这波不亏',
      '日常小牌贪牌算牌',
      '小牌也存在很多进攻的思路',
    ],
    mustRead: [
      '根据期望进攻思路',
      '进攻思路',
      '按期望收益还是可以做清',
      '这牌给你打你会做清吗',
      '优势进攻做大思路',
      '川麻里性价比最高的就是自摸',
    ],
  },
  {
    code: 'D',
    name: '防守与逃跑',
    summary: '该怂就怂，躲大牌比做小牌重要',
    titles: [
      '面对大牌逃跑思路',
      '该跑就跑见机行事',
      '该怂就怂不然挨个满的',
      '牌无风险尽可一试',
      '经常顺放上家但也要看情况',
      '弱势局跑得掉很重要',
      '防守局是比较费脑筋',
      '躲大牌很关键',
      '没有风险不要浪费机会有风险不要对刚',
      '捏住关键防守反击',
      '不要以为自己牌好也许别人的更好',
      '防御思路+对家反面教材',
      '弱势做牌',
      '弱势烂叫寻找出路',
      '缺章弱势防守反击',
      '防守思路',
      '逆风思路',
      '有人说想看烂牌防守',
      '躲得掉也是福',
      '逃跑思路',
      '不得不点海底的时候降低损失',
      '灵活防守',
      '算牌防守',
      '识别危险是进阶的必修课',
      '第一局是肯定逃第二局是太早叫',
      '逆风策略',
      '关键章点炮还是继续防守',
    ],
    mustRead: [
      '该怂就怂不然挨个满的',
      '面对大牌逃跑思路',
      '逃跑思路',
      '识别危险是进阶的必修课',
      '不得不点海底的时候降低损失',
      '灵活防守',
    ],
  },
  {
    code: 'I',
    name: '形势与信息',
    summary: '一看手牌，二看缺章，三看牌河',
    titles: [
      '两家收条无奈占筒',
      '牌不上章找叫思路',
      '估出4万很可能还在才这样打进章效率最大该大8筒',
      '牌局变换太快思路跟上形势变化',
      '估算手牌步步为营转守为攻',
      '算牌捏牌避坑干货',
      '利用关键牌信息',
      '牌墙短了关键选叫',
      '舍弃两边捏好关键张',
      '局势不对及时调整思路',
      '守好章牌就胜利一半了',
      '看清形势',
      '关键信息利用好',
      '应时而异落子不悔',
      '关键选择是否冒险',
      '顺势而为',
      '两家收牌抢一下牌',
      '局势变化利用细节',
      '得看局势',
      '三家收牌算牌',
      '两家收灵活收牌#麻将教学',
      '5万捏久了更危险',
      '两边断章也不一定胡',
      '及时调整方向',
      '根据实际收牌调整进章方向',
      '一家收牌时候的一点小技巧',
      '如果两家收选卡章',
      '算牌重要结合数学更效率',
      '利用细节去推测关键时候发挥大作用',
      '特殊缺章特殊选叫',
      '一看手牌二看缺章顺势而为',
      '利用孤章找叫思路',
      '二对二势均力敌不一定还是需要根据情况',
      '当牌局实际缺章发生变化调整策略',
    ],
    mustRead: [
      '看清形势',
      '两家收条无奈占筒',
      '守好章牌就胜利一半了',
      '利用关键牌信息',
      '如果两家收选卡章',
      '估出4万很可能还在才这样打进章效率最大该大8筒',
    ],
  },
  {
    code: 'P',
    name: '对子搭子与牌效率',
    summary: '对子不能无脑留，效率优先',
    titles: [
      '对子多了不一定好',
      '二筒碰早了结果.......',
      '对子多了找叫思路',
      '杠或不杠看牌质量',
      '拆45条还是见仁见智吧',
      '五万八万看似相同实际不同',
      '拆对子还是搭子',
      '保留五万进章多',
      '走还是按杠',
      '思辨对子处理',
      '悄防杠上花这局经验超实用',
      '利用率',
      '对子不能无脑留',
      '要不要碰一点思路',
      '杠或不杠权衡取舍',
      '如果万子很差或者2条出来没人要就考虑258',
      '你会杠上打2筒吗',
      '对子多了的情况下的不同思路',
      '怕点被人杠上炮这局给你一点参考',
    ],
    mustRead: [
      '对子不能无脑留',
      '拆对子还是搭子',
      '对子多了不一定好',
      '杠或不杠看牌质量',
      '二筒碰早了结果.......',
    ],
  },
  {
    code: 'T',
    name: '找叫与选叫',
    summary: '叫的质量 > 有叫没叫',
    titles: [
      '下家7筒打得好暂时不要叫',
      '选择做牌就要遭',
      '选叫思路',
      '辩有叫是否大于天',
      '雨和叫有时候只能选一个',
      '这牌你选二筒还是五八筒',
      '接不接',
      '摸到8条你会胡对出吗',
      '上家基本做起了还不让我下叫',
      '日常小牌选叫思路',
      '如果外面有大牌选对路很重要',
      '你会选14还是69',
      '牌局判断下叫选择',
      '之后很容易再下叫就留住',
      '预留叫口',
      '摸5胡7的缘分',
      '双线并进',
      '优质叫口',
      '杠上选择要不要叫',
      '单选一张爱恨一瞬',
      '如果两家要就胡卡章',
      '诱人的东西可能最危险#麻将教学',
      '兼容情况下选大的集合',
      '不忘初心方得始终#麻将教学',
      '根据实际情况选择放弃一上听',
      '对出还是卡章一点思路',
      '潇式麻将法则',
      '叫不见得好赶紧跑',
      '你会胡14条还是和我一样',
      '结合实际情况选择下叫方向有助提高胡牌效率',
      '下叫还是捏牌',
      '卡章的本质也是搭子叫',
    ],
    mustRead: [
      '下家7筒打得好暂时不要叫',
      '辩有叫是否大于天',
      '潇式麻将法则',
      '这牌你选二筒还是五八筒',
      '你会选14还是69',
      '下叫还是捏牌',
    ],
  },
  {
    code: 'S',
    name: '单钓七对与特殊牌型',
    summary: '特殊牌型也要按概率决策',
    titles: [
      '下家要打单钓我',
      '顺势找叫顺便七对',
      '下家两杠大单钓如何逃跑',
      '大单钓还是七对这把教给你诀窍',
      '大牌对刚得分情况',
      '单钓技巧弱势逆袭',
      '刚打缺就遭一个龙七对',
      '舍弃大对',
      '七对思路',
      '单钓进攻',
      '龙七思路',
      '七对遇碰牌这局教你应对技巧#麻将教学',
      '缺章不利单钓选叫的实用技巧',
      '占用率的问题单钓也考虑这一点',
      '清一色顺势不强求',
      '大单钓难选叫这把交给你诀窍',
      '七对还是大单钓一点思路',
    ],
    mustRead: [
      '大单钓还是七对这把教给你诀窍',
      '顺势找叫顺便七对',
      '单钓技巧弱势逆袭',
      '刚打缺就遭一个龙七对',
    ],
  },
  {
    code: 'G',
    name: '整局实战与复盘',
    summary: '综合决策 + 反面教材',
    titles: [
      '且攻且守',
      '策略失误反面教材',
      '一般不这样打',
      '做牌思路',
      '寻找出路',
      '反面教材',
      '四局连播',
      '这牌打得有问题吗',
      '思路正确',
      '找寻出路',
      '思考题',
      '一般情况不这样做牌',
    ],
    mustRead: [
      '思考题',
      '策略失误反面教材',
      '反面教材',
      '策略失误反面教材',
      '反面教材',
      '四局连播',
    ],
  },
  {
    code: 'M',
    name: '心态与理念',
    summary: '运气是短期的方差，打法才是长期的期望',
    titles: [
      '短期看运气长期看思路',
      '不能无脑按牌经打牌',
      '一念天堂一念地狱',
      '淡定不了',
      '短期看运气长期看牌技',
      '尽人事听天命',
      '保持心态稳定发挥',
      '理解好队友和对手的辩证关系',
      '坚持原则',
      '运气的事真没法说',
      '换三运气很重要',
      '要有自己的原则知行合一',
      '努力争取也看运气上家海底打的好',
      '计划很好差点运气',
      '运气无理平和操作',
      '运气时好时坏关键的是理念',
      '小牌才是常态',
      '运气长期来说是公平的',
      '长期来说统计和期望非常重要',
      '定好方向坚定执行',
      '如果手气好一点',
      '懂得取舍',
      '单场来看真的是7分手气3分技术',
      '保持理智',
      '运气这个东西说不清楚的',
      '神奇的牌运',
      '这运气好还是撇',
      '形式危机是运气还是判断',
      '保持心态',
      '运气波动',
      '心态好就是胜利',
      '运气玄学',
      '莫道君行早更有早行人',
      '因祸得福',
      '下次我还是会这样打',
      '运动员需要好的心态打麻将也一样',
      '这次虽错过但长期坚持必有收获',
      '这个牌4分手肯定不得走的',
      '这个牌越打越精神',
      '守住理性不受诱惑',
      '除非有较高把握一般不这样',
      '打麻将是运气重要还是打法重要呢',
      '正确的打法贵在长期坚持',
    ],
    mustRead: [
      '短期看运气长期看思路',
      '长期来说统计和期望非常重要',
      '打麻将是运气重要还是打法重要呢',
      '小牌才是常态',
      '要有自己的原则知行合一',
    ],
  },
  {
    code: 'X',
    name: '生活互动',
    summary: '好运/节日/闲聊，不入课表',
    titles: [
      '人要有梦想万一实现了呢',
      '节日快乐干货分享',
      '好运常在顺顺利利',
      '祝大家五一快乐',
      '这样的下家小姐姐你们喜欢吗',
      '虽然绕路但是必要',
      '好运日常',
      '牌太散取舍思路',
      '不及预期调整思路',
      '丝滑手气看完顺顺顺',
      '看了心情好心情好运势好',
      '日常好运来',
      '日常好运点赞分享',
      '小小单行道拿下',
      '新年快乐清照茶府春节不打烊',
      '牌势随好见好就收',
      '为了涨翻放弃涨翻',
      '说顺也不顺',
      '三局连播好运连连',
      '以人为镜可以明得失',
      '坚定执行平常心',
      '不忘初心方得始终',
      '简单小牌美好小运',
      '开年好运生活顺顺',
      '平平淡淡简单美好',
      '排序不对打啥都是错排序号乱打都对',
      '且进且退进退宜得',
      '神奇的牌神奇的运',
      '看完这期视频我看谁还不会利用机麻福利',
    ],
    mustRead: [
    ],
  },
]

/** 4 层递进学习路径（按决策依赖关系编排，非按簇大小） */
export const xiaoshiPath: readonly PathLayer[] = [
  {
    id: 'L1',
    name: '底层操作系统',
    weeks: '约2周',
    goal: '先接受"运气不可控、打法可控"，否则后面所有技术都会在执行时变形。',
    clusters: ['M'],
  },
  {
    id: 'L2',
    name: '出牌基本功',
    weeks: '3-5周',
    goal: '手牌效率与叫口质量——80% 局牌的核心战场。',
    clusters: ['P', 'T'],
  },
  {
    id: 'L3',
    name: '牌桌博弈',
    weeks: '6-10周',
    goal: '读牌河信息，做出攻/守/贪/逃的正确切换。语料最大区，按周主题选学5-8期，重复验证的跳过。',
    clusters: ['I', 'E', 'D'],
  },
  {
    id: 'L4',
    name: '特殊牌型与整局复盘',
    weeks: '长期穿插',
    goal: 'S 类精读；G 类每月挑 1-2 期做完整复盘，跟踪分歧率趋势。',
    clusters: ['S', 'G'],
  },
]

/** 展平课程清单：每期一条，含簇归属 + 层级 + 是否精读。X 类不进课表（layerId 为 null）。 */
export const xiaoshiLessons: readonly XioshiLesson[] = [
  { title: '根据期望进攻思路', cluster: 'E', mustRead: true, layerId: 'L3' },
  { title: '这牌给你打你会做清吗', cluster: 'E', mustRead: true, layerId: 'L3' },
  { title: '按期望收益还是可以做清', cluster: 'E', mustRead: true, layerId: 'L3' },
  { title: '稍微进攻意外之喜', cluster: 'E', mustRead: false, layerId: 'L3' },
  { title: '适度把握小机会', cluster: 'E', mustRead: false, layerId: 'L3' },
  { title: '见炮就跑使劲贪都不好', cluster: 'E', mustRead: false, layerId: 'L3' },
  { title: '优势进攻做大思路', cluster: 'E', mustRead: true, layerId: 'L3' },
  { title: '常理推断不做大对', cluster: 'E', mustRead: false, layerId: 'L3' },
  { title: '起手优势贪牌思路', cluster: 'E', mustRead: false, layerId: 'L3' },
  { title: '进攻思路', cluster: 'E', mustRead: true, layerId: 'L3' },
  { title: '适当做清两局连播', cluster: 'E', mustRead: false, layerId: 'L3' },
  { title: '处理好日常小牌的小贪和逃跑很重要', cluster: 'E', mustRead: false, layerId: 'L3' },
  { title: '缺牌优势按番种性价比来尽早自摸才对', cluster: 'E', mustRead: false, layerId: 'L3' },
  { title: '不该贪的时候绝对不会贪', cluster: 'E', mustRead: false, layerId: 'L3' },
  { title: '步步做大', cluster: 'E', mustRead: false, layerId: 'L3' },
  { title: '贪一下咋了', cluster: 'E', mustRead: false, layerId: 'L3' },
  { title: '进攻还是防守灵活思路', cluster: 'E', mustRead: false, layerId: 'L3' },
  { title: '小牌不贪策略尽力', cluster: 'E', mustRead: false, layerId: 'L3' },
  { title: '对手做清逃跑思路', cluster: 'E', mustRead: false, layerId: 'L3' },
  { title: '三家不要进攻思路', cluster: 'E', mustRead: false, layerId: 'L3' },
  { title: '小贪思路', cluster: 'E', mustRead: false, layerId: 'L3' },
  { title: '雨分可贵自摸价更高', cluster: 'E', mustRead: false, layerId: 'L3' },
  { title: '两家收牌小贪一下', cluster: 'E', mustRead: false, layerId: 'L3' },
  { title: '钓牌找思路加上概率期望指导抉择', cluster: 'E', mustRead: false, layerId: 'L3' },
  { title: '有机会想进攻但是防守也要算好', cluster: 'E', mustRead: false, layerId: 'L3' },
  { title: '带杠自摸YYDS', cluster: 'E', mustRead: false, layerId: 'L3' },
  { title: '三家不要', cluster: 'E', mustRead: false, layerId: 'L3' },
  { title: '寻找机会', cluster: 'E', mustRead: false, layerId: 'L3' },
  { title: '同行走了把握机会', cluster: 'E', mustRead: false, layerId: 'L3' },
  { title: '别人做清有风险也有机会', cluster: 'E', mustRead: false, layerId: 'L3' },
  { title: '该贪就该', cluster: 'E', mustRead: false, layerId: 'L3' },
  { title: '堵34条概率更大', cluster: 'E', mustRead: false, layerId: 'L3' },
  { title: '两家不要做清找叫', cluster: 'E', mustRead: false, layerId: 'L3' },
  { title: '贪清思路', cluster: 'E', mustRead: false, layerId: 'L3' },
  { title: '自摸技巧', cluster: 'E', mustRead: false, layerId: 'L3' },
  { title: '做清路上有取有舍', cluster: 'E', mustRead: false, layerId: 'L3' },
  { title: '两家收做清思路', cluster: 'E', mustRead: false, layerId: 'L3' },
  { title: '没有风险顺便进攻', cluster: 'E', mustRead: false, layerId: 'L3' },
  { title: '做清一色顺势而为', cluster: 'E', mustRead: false, layerId: 'L3' },
  { title: '去做清吧做不被定义的清一色', cluster: 'E', mustRead: false, layerId: 'L3' },
  { title: '评估机会和风险', cluster: 'E', mustRead: false, layerId: 'L3' },
  { title: '有时候只有一张了也要贪有时候还有两三张也要跑', cluster: 'E', mustRead: false, layerId: 'L3' },
  { title: '这牌你会做清吗#麻将教学', cluster: 'E', mustRead: false, layerId: 'L3' },
  { title: '用期望量化进牌效率#麻将教学', cluster: 'E', mustRead: false, layerId: 'L3' },
  { title: '这牌贪不下去了', cluster: 'E', mustRead: false, layerId: 'L3' },
  { title: '这牌该贪吗', cluster: 'E', mustRead: false, layerId: 'L3' },
  { title: '期望收益权衡取舍', cluster: 'E', mustRead: false, layerId: 'L3' },
  { title: '川麻里性价比最高的就是自摸', cluster: 'E', mustRead: true, layerId: 'L3' },
  { title: '双方博弈', cluster: 'E', mustRead: false, layerId: 'L3' },
  { title: '做清路上的进退把握', cluster: 'E', mustRead: false, layerId: 'L3' },
  { title: '做清进退', cluster: 'E', mustRead: false, layerId: 'L3' },
  { title: '牌局变化逃跑变进攻', cluster: 'E', mustRead: false, layerId: 'L3' },
  { title: '早叫想贪但也要合适些', cluster: 'E', mustRead: false, layerId: 'L3' },
  { title: '虽有性价比', cluster: 'E', mustRead: false, layerId: 'L3' },
  { title: '缺章弱势手牌优势', cluster: 'E', mustRead: false, layerId: 'L3' },
  { title: '对手做清灵活防守#麻将技术', cluster: 'E', mustRead: false, layerId: 'L3' },
  { title: '贪攻的时候尽量回避风险', cluster: 'E', mustRead: false, layerId: 'L3' },
  { title: '识别机会该贪就贪', cluster: 'E', mustRead: false, layerId: 'L3' },
  { title: '碰牌换叫提升胡牌概率', cluster: 'E', mustRead: false, layerId: 'L3' },
  { title: '进攻思路略有不同寻常', cluster: 'E', mustRead: false, layerId: 'L3' },
  { title: '缺章变化进攻思路', cluster: 'E', mustRead: false, layerId: 'L3' },
  { title: '这个卡章必贪', cluster: 'E', mustRead: false, layerId: 'L3' },
  { title: '概率问题', cluster: 'E', mustRead: false, layerId: 'L3' },
  { title: '进攻思路把握优势', cluster: 'E', mustRead: false, layerId: 'L3' },
  { title: '根据局势制定进攻策略', cluster: 'E', mustRead: false, layerId: 'L3' },
  { title: '牌局进程选择贪到极致', cluster: 'E', mustRead: false, layerId: 'L3' },
  { title: '三家收做清选叫思路', cluster: 'E', mustRead: false, layerId: 'L3' },
  { title: '自摸多多', cluster: 'E', mustRead: false, layerId: 'L3' },
  { title: '做不做清进退有度', cluster: 'E', mustRead: false, layerId: 'L3' },
  { title: '缺章弱势分析牌局制定进攻', cluster: 'E', mustRead: false, layerId: 'L3' },
  { title: '该放就放机会是自己把握的', cluster: 'E', mustRead: false, layerId: 'L3' },
  { title: '高手都知道的细节海底是机会', cluster: 'E', mustRead: false, layerId: 'L3' },
  { title: '真的是最不爱做清一色的麻将博主', cluster: 'E', mustRead: false, layerId: 'L3' },
  { title: '以小博大这波不亏', cluster: 'E', mustRead: false, layerId: 'L3' },
  { title: '日常小牌贪牌算牌', cluster: 'E', mustRead: false, layerId: 'L3' },
  { title: '小牌也存在很多进攻的思路', cluster: 'E', mustRead: false, layerId: 'L3' },
  { title: '面对大牌逃跑思路', cluster: 'D', mustRead: true, layerId: 'L3' },
  { title: '该跑就跑见机行事', cluster: 'D', mustRead: false, layerId: 'L3' },
  { title: '该怂就怂不然挨个满的', cluster: 'D', mustRead: true, layerId: 'L3' },
  { title: '牌无风险尽可一试', cluster: 'D', mustRead: false, layerId: 'L3' },
  { title: '经常顺放上家但也要看情况', cluster: 'D', mustRead: false, layerId: 'L3' },
  { title: '弱势局跑得掉很重要', cluster: 'D', mustRead: false, layerId: 'L3' },
  { title: '防守局是比较费脑筋', cluster: 'D', mustRead: false, layerId: 'L3' },
  { title: '躲大牌很关键', cluster: 'D', mustRead: false, layerId: 'L3' },
  { title: '没有风险不要浪费机会有风险不要对刚', cluster: 'D', mustRead: false, layerId: 'L3' },
  { title: '捏住关键防守反击', cluster: 'D', mustRead: false, layerId: 'L3' },
  { title: '不要以为自己牌好也许别人的更好', cluster: 'D', mustRead: false, layerId: 'L3' },
  { title: '防御思路+对家反面教材', cluster: 'D', mustRead: false, layerId: 'L3' },
  { title: '弱势做牌', cluster: 'D', mustRead: false, layerId: 'L3' },
  { title: '弱势烂叫寻找出路', cluster: 'D', mustRead: false, layerId: 'L3' },
  { title: '缺章弱势防守反击', cluster: 'D', mustRead: false, layerId: 'L3' },
  { title: '防守思路', cluster: 'D', mustRead: false, layerId: 'L3' },
  { title: '逆风思路', cluster: 'D', mustRead: false, layerId: 'L3' },
  { title: '有人说想看烂牌防守', cluster: 'D', mustRead: false, layerId: 'L3' },
  { title: '躲得掉也是福', cluster: 'D', mustRead: false, layerId: 'L3' },
  { title: '逃跑思路', cluster: 'D', mustRead: true, layerId: 'L3' },
  { title: '不得不点海底的时候降低损失', cluster: 'D', mustRead: true, layerId: 'L3' },
  { title: '灵活防守', cluster: 'D', mustRead: true, layerId: 'L3' },
  { title: '算牌防守', cluster: 'D', mustRead: false, layerId: 'L3' },
  { title: '识别危险是进阶的必修课', cluster: 'D', mustRead: true, layerId: 'L3' },
  { title: '第一局是肯定逃第二局是太早叫', cluster: 'D', mustRead: false, layerId: 'L3' },
  { title: '逆风策略', cluster: 'D', mustRead: false, layerId: 'L3' },
  { title: '关键章点炮还是继续防守', cluster: 'D', mustRead: false, layerId: 'L3' },
  { title: '两家收条无奈占筒', cluster: 'I', mustRead: true, layerId: 'L3' },
  { title: '牌不上章找叫思路', cluster: 'I', mustRead: false, layerId: 'L3' },
  { title: '估出4万很可能还在才这样打进章效率最大该大8筒', cluster: 'I', mustRead: true, layerId: 'L3' },
  { title: '牌局变换太快思路跟上形势变化', cluster: 'I', mustRead: false, layerId: 'L3' },
  { title: '估算手牌步步为营转守为攻', cluster: 'I', mustRead: false, layerId: 'L3' },
  { title: '算牌捏牌避坑干货', cluster: 'I', mustRead: false, layerId: 'L3' },
  { title: '利用关键牌信息', cluster: 'I', mustRead: true, layerId: 'L3' },
  { title: '牌墙短了关键选叫', cluster: 'I', mustRead: false, layerId: 'L3' },
  { title: '舍弃两边捏好关键张', cluster: 'I', mustRead: false, layerId: 'L3' },
  { title: '局势不对及时调整思路', cluster: 'I', mustRead: false, layerId: 'L3' },
  { title: '守好章牌就胜利一半了', cluster: 'I', mustRead: true, layerId: 'L3' },
  { title: '看清形势', cluster: 'I', mustRead: true, layerId: 'L3' },
  { title: '关键信息利用好', cluster: 'I', mustRead: false, layerId: 'L3' },
  { title: '应时而异落子不悔', cluster: 'I', mustRead: false, layerId: 'L3' },
  { title: '关键选择是否冒险', cluster: 'I', mustRead: false, layerId: 'L3' },
  { title: '顺势而为', cluster: 'I', mustRead: false, layerId: 'L3' },
  { title: '两家收牌抢一下牌', cluster: 'I', mustRead: false, layerId: 'L3' },
  { title: '局势变化利用细节', cluster: 'I', mustRead: false, layerId: 'L3' },
  { title: '得看局势', cluster: 'I', mustRead: false, layerId: 'L3' },
  { title: '三家收牌算牌', cluster: 'I', mustRead: false, layerId: 'L3' },
  { title: '两家收灵活收牌#麻将教学', cluster: 'I', mustRead: false, layerId: 'L3' },
  { title: '5万捏久了更危险', cluster: 'I', mustRead: false, layerId: 'L3' },
  { title: '两边断章也不一定胡', cluster: 'I', mustRead: false, layerId: 'L3' },
  { title: '及时调整方向', cluster: 'I', mustRead: false, layerId: 'L3' },
  { title: '根据实际收牌调整进章方向', cluster: 'I', mustRead: false, layerId: 'L3' },
  { title: '一家收牌时候的一点小技巧', cluster: 'I', mustRead: false, layerId: 'L3' },
  { title: '如果两家收选卡章', cluster: 'I', mustRead: true, layerId: 'L3' },
  { title: '算牌重要结合数学更效率', cluster: 'I', mustRead: false, layerId: 'L3' },
  { title: '利用细节去推测关键时候发挥大作用', cluster: 'I', mustRead: false, layerId: 'L3' },
  { title: '特殊缺章特殊选叫', cluster: 'I', mustRead: false, layerId: 'L3' },
  { title: '一看手牌二看缺章顺势而为', cluster: 'I', mustRead: false, layerId: 'L3' },
  { title: '利用孤章找叫思路', cluster: 'I', mustRead: false, layerId: 'L3' },
  { title: '二对二势均力敌不一定还是需要根据情况', cluster: 'I', mustRead: false, layerId: 'L3' },
  { title: '当牌局实际缺章发生变化调整策略', cluster: 'I', mustRead: false, layerId: 'L3' },
  { title: '对子多了不一定好', cluster: 'P', mustRead: true, layerId: 'L2' },
  { title: '二筒碰早了结果.......', cluster: 'P', mustRead: true, layerId: 'L2' },
  { title: '对子多了找叫思路', cluster: 'P', mustRead: false, layerId: 'L2' },
  { title: '杠或不杠看牌质量', cluster: 'P', mustRead: true, layerId: 'L2' },
  { title: '拆45条还是见仁见智吧', cluster: 'P', mustRead: false, layerId: 'L2' },
  { title: '五万八万看似相同实际不同', cluster: 'P', mustRead: false, layerId: 'L2' },
  { title: '拆对子还是搭子', cluster: 'P', mustRead: true, layerId: 'L2' },
  { title: '保留五万进章多', cluster: 'P', mustRead: false, layerId: 'L2' },
  { title: '走还是按杠', cluster: 'P', mustRead: false, layerId: 'L2' },
  { title: '思辨对子处理', cluster: 'P', mustRead: false, layerId: 'L2' },
  { title: '悄防杠上花这局经验超实用', cluster: 'P', mustRead: false, layerId: 'L2' },
  { title: '利用率', cluster: 'P', mustRead: false, layerId: 'L2' },
  { title: '对子不能无脑留', cluster: 'P', mustRead: true, layerId: 'L2' },
  { title: '要不要碰一点思路', cluster: 'P', mustRead: false, layerId: 'L2' },
  { title: '杠或不杠权衡取舍', cluster: 'P', mustRead: false, layerId: 'L2' },
  { title: '如果万子很差或者2条出来没人要就考虑258', cluster: 'P', mustRead: false, layerId: 'L2' },
  { title: '你会杠上打2筒吗', cluster: 'P', mustRead: false, layerId: 'L2' },
  { title: '对子多了的情况下的不同思路', cluster: 'P', mustRead: false, layerId: 'L2' },
  { title: '怕点被人杠上炮这局给你一点参考', cluster: 'P', mustRead: false, layerId: 'L2' },
  { title: '下家7筒打得好暂时不要叫', cluster: 'T', mustRead: true, layerId: 'L2' },
  { title: '选择做牌就要遭', cluster: 'T', mustRead: false, layerId: 'L2' },
  { title: '选叫思路', cluster: 'T', mustRead: false, layerId: 'L2' },
  { title: '辩有叫是否大于天', cluster: 'T', mustRead: true, layerId: 'L2' },
  { title: '雨和叫有时候只能选一个', cluster: 'T', mustRead: false, layerId: 'L2' },
  { title: '这牌你选二筒还是五八筒', cluster: 'T', mustRead: true, layerId: 'L2' },
  { title: '接不接', cluster: 'T', mustRead: false, layerId: 'L2' },
  { title: '摸到8条你会胡对出吗', cluster: 'T', mustRead: false, layerId: 'L2' },
  { title: '上家基本做起了还不让我下叫', cluster: 'T', mustRead: false, layerId: 'L2' },
  { title: '日常小牌选叫思路', cluster: 'T', mustRead: false, layerId: 'L2' },
  { title: '如果外面有大牌选对路很重要', cluster: 'T', mustRead: false, layerId: 'L2' },
  { title: '你会选14还是69', cluster: 'T', mustRead: true, layerId: 'L2' },
  { title: '牌局判断下叫选择', cluster: 'T', mustRead: false, layerId: 'L2' },
  { title: '之后很容易再下叫就留住', cluster: 'T', mustRead: false, layerId: 'L2' },
  { title: '预留叫口', cluster: 'T', mustRead: false, layerId: 'L2' },
  { title: '摸5胡7的缘分', cluster: 'T', mustRead: false, layerId: 'L2' },
  { title: '双线并进', cluster: 'T', mustRead: false, layerId: 'L2' },
  { title: '优质叫口', cluster: 'T', mustRead: false, layerId: 'L2' },
  { title: '杠上选择要不要叫', cluster: 'T', mustRead: false, layerId: 'L2' },
  { title: '单选一张爱恨一瞬', cluster: 'T', mustRead: false, layerId: 'L2' },
  { title: '如果两家要就胡卡章', cluster: 'T', mustRead: false, layerId: 'L2' },
  { title: '诱人的东西可能最危险#麻将教学', cluster: 'T', mustRead: false, layerId: 'L2' },
  { title: '兼容情况下选大的集合', cluster: 'T', mustRead: false, layerId: 'L2' },
  { title: '不忘初心方得始终#麻将教学', cluster: 'T', mustRead: false, layerId: 'L2' },
  { title: '根据实际情况选择放弃一上听', cluster: 'T', mustRead: false, layerId: 'L2' },
  { title: '对出还是卡章一点思路', cluster: 'T', mustRead: false, layerId: 'L2' },
  { title: '潇式麻将法则', cluster: 'T', mustRead: true, layerId: 'L2' },
  { title: '叫不见得好赶紧跑', cluster: 'T', mustRead: false, layerId: 'L2' },
  { title: '你会胡14条还是和我一样', cluster: 'T', mustRead: false, layerId: 'L2' },
  { title: '结合实际情况选择下叫方向有助提高胡牌效率', cluster: 'T', mustRead: false, layerId: 'L2' },
  { title: '下叫还是捏牌', cluster: 'T', mustRead: true, layerId: 'L2' },
  { title: '卡章的本质也是搭子叫', cluster: 'T', mustRead: false, layerId: 'L2' },
  { title: '下家要打单钓我', cluster: 'S', mustRead: false, layerId: 'L4' },
  { title: '顺势找叫顺便七对', cluster: 'S', mustRead: true, layerId: 'L4' },
  { title: '下家两杠大单钓如何逃跑', cluster: 'S', mustRead: false, layerId: 'L4' },
  { title: '大单钓还是七对这把教给你诀窍', cluster: 'S', mustRead: true, layerId: 'L4' },
  { title: '大牌对刚得分情况', cluster: 'S', mustRead: false, layerId: 'L4' },
  { title: '单钓技巧弱势逆袭', cluster: 'S', mustRead: true, layerId: 'L4' },
  { title: '刚打缺就遭一个龙七对', cluster: 'S', mustRead: true, layerId: 'L4' },
  { title: '舍弃大对', cluster: 'S', mustRead: false, layerId: 'L4' },
  { title: '七对思路', cluster: 'S', mustRead: false, layerId: 'L4' },
  { title: '单钓进攻', cluster: 'S', mustRead: false, layerId: 'L4' },
  { title: '龙七思路', cluster: 'S', mustRead: false, layerId: 'L4' },
  { title: '七对遇碰牌这局教你应对技巧#麻将教学', cluster: 'S', mustRead: false, layerId: 'L4' },
  { title: '缺章不利单钓选叫的实用技巧', cluster: 'S', mustRead: false, layerId: 'L4' },
  { title: '占用率的问题单钓也考虑这一点', cluster: 'S', mustRead: false, layerId: 'L4' },
  { title: '清一色顺势不强求', cluster: 'S', mustRead: false, layerId: 'L4' },
  { title: '大单钓难选叫这把交给你诀窍', cluster: 'S', mustRead: false, layerId: 'L4' },
  { title: '七对还是大单钓一点思路', cluster: 'S', mustRead: false, layerId: 'L4' },
  { title: '且攻且守', cluster: 'G', mustRead: false, layerId: 'L4' },
  { title: '策略失误反面教材', cluster: 'G', mustRead: true, layerId: 'L4' },
  { title: '一般不这样打', cluster: 'G', mustRead: false, layerId: 'L4' },
  { title: '做牌思路', cluster: 'G', mustRead: false, layerId: 'L4' },
  { title: '寻找出路', cluster: 'G', mustRead: false, layerId: 'L4' },
  { title: '反面教材', cluster: 'G', mustRead: true, layerId: 'L4' },
  { title: '四局连播', cluster: 'G', mustRead: true, layerId: 'L4' },
  { title: '这牌打得有问题吗', cluster: 'G', mustRead: false, layerId: 'L4' },
  { title: '思路正确', cluster: 'G', mustRead: false, layerId: 'L4' },
  { title: '找寻出路', cluster: 'G', mustRead: false, layerId: 'L4' },
  { title: '思考题', cluster: 'G', mustRead: true, layerId: 'L4' },
  { title: '一般情况不这样做牌', cluster: 'G', mustRead: false, layerId: 'L4' },
  { title: '短期看运气长期看思路', cluster: 'M', mustRead: true, layerId: 'L1' },
  { title: '不能无脑按牌经打牌', cluster: 'M', mustRead: false, layerId: 'L1' },
  { title: '一念天堂一念地狱', cluster: 'M', mustRead: false, layerId: 'L1' },
  { title: '淡定不了', cluster: 'M', mustRead: false, layerId: 'L1' },
  { title: '短期看运气长期看牌技', cluster: 'M', mustRead: false, layerId: 'L1' },
  { title: '尽人事听天命', cluster: 'M', mustRead: false, layerId: 'L1' },
  { title: '保持心态稳定发挥', cluster: 'M', mustRead: false, layerId: 'L1' },
  { title: '理解好队友和对手的辩证关系', cluster: 'M', mustRead: false, layerId: 'L1' },
  { title: '坚持原则', cluster: 'M', mustRead: false, layerId: 'L1' },
  { title: '运气的事真没法说', cluster: 'M', mustRead: false, layerId: 'L1' },
  { title: '换三运气很重要', cluster: 'M', mustRead: false, layerId: 'L1' },
  { title: '要有自己的原则知行合一', cluster: 'M', mustRead: true, layerId: 'L1' },
  { title: '努力争取也看运气上家海底打的好', cluster: 'M', mustRead: false, layerId: 'L1' },
  { title: '计划很好差点运气', cluster: 'M', mustRead: false, layerId: 'L1' },
  { title: '运气无理平和操作', cluster: 'M', mustRead: false, layerId: 'L1' },
  { title: '运气时好时坏关键的是理念', cluster: 'M', mustRead: false, layerId: 'L1' },
  { title: '小牌才是常态', cluster: 'M', mustRead: true, layerId: 'L1' },
  { title: '运气长期来说是公平的', cluster: 'M', mustRead: false, layerId: 'L1' },
  { title: '长期来说统计和期望非常重要', cluster: 'M', mustRead: true, layerId: 'L1' },
  { title: '定好方向坚定执行', cluster: 'M', mustRead: false, layerId: 'L1' },
  { title: '如果手气好一点', cluster: 'M', mustRead: false, layerId: 'L1' },
  { title: '懂得取舍', cluster: 'M', mustRead: false, layerId: 'L1' },
  { title: '单场来看真的是7分手气3分技术', cluster: 'M', mustRead: false, layerId: 'L1' },
  { title: '保持理智', cluster: 'M', mustRead: false, layerId: 'L1' },
  { title: '运气这个东西说不清楚的', cluster: 'M', mustRead: false, layerId: 'L1' },
  { title: '神奇的牌运', cluster: 'M', mustRead: false, layerId: 'L1' },
  { title: '这运气好还是撇', cluster: 'M', mustRead: false, layerId: 'L1' },
  { title: '形式危机是运气还是判断', cluster: 'M', mustRead: false, layerId: 'L1' },
  { title: '保持心态', cluster: 'M', mustRead: false, layerId: 'L1' },
  { title: '运气波动', cluster: 'M', mustRead: false, layerId: 'L1' },
  { title: '心态好就是胜利', cluster: 'M', mustRead: false, layerId: 'L1' },
  { title: '运气玄学', cluster: 'M', mustRead: false, layerId: 'L1' },
  { title: '莫道君行早更有早行人', cluster: 'M', mustRead: false, layerId: 'L1' },
  { title: '因祸得福', cluster: 'M', mustRead: false, layerId: 'L1' },
  { title: '下次我还是会这样打', cluster: 'M', mustRead: false, layerId: 'L1' },
  { title: '运动员需要好的心态打麻将也一样', cluster: 'M', mustRead: false, layerId: 'L1' },
  { title: '这次虽错过但长期坚持必有收获', cluster: 'M', mustRead: false, layerId: 'L1' },
  { title: '这个牌4分手肯定不得走的', cluster: 'M', mustRead: false, layerId: 'L1' },
  { title: '这个牌越打越精神', cluster: 'M', mustRead: false, layerId: 'L1' },
  { title: '守住理性不受诱惑', cluster: 'M', mustRead: false, layerId: 'L1' },
  { title: '除非有较高把握一般不这样', cluster: 'M', mustRead: false, layerId: 'L1' },
  { title: '打麻将是运气重要还是打法重要呢', cluster: 'M', mustRead: true, layerId: 'L1' },
  { title: '正确的打法贵在长期坚持', cluster: 'M', mustRead: false, layerId: 'L1' },
  { title: '人要有梦想万一实现了呢', cluster: 'X', mustRead: false, layerId: null },
  { title: '节日快乐干货分享', cluster: 'X', mustRead: false, layerId: null },
  { title: '好运常在顺顺利利', cluster: 'X', mustRead: false, layerId: null },
  { title: '祝大家五一快乐', cluster: 'X', mustRead: false, layerId: null },
  { title: '这样的下家小姐姐你们喜欢吗', cluster: 'X', mustRead: false, layerId: null },
  { title: '虽然绕路但是必要', cluster: 'X', mustRead: false, layerId: null },
  { title: '好运日常', cluster: 'X', mustRead: false, layerId: null },
  { title: '牌太散取舍思路', cluster: 'X', mustRead: false, layerId: null },
  { title: '不及预期调整思路', cluster: 'X', mustRead: false, layerId: null },
  { title: '丝滑手气看完顺顺顺', cluster: 'X', mustRead: false, layerId: null },
  { title: '看了心情好心情好运势好', cluster: 'X', mustRead: false, layerId: null },
  { title: '日常好运来', cluster: 'X', mustRead: false, layerId: null },
  { title: '日常好运点赞分享', cluster: 'X', mustRead: false, layerId: null },
  { title: '小小单行道拿下', cluster: 'X', mustRead: false, layerId: null },
  { title: '新年快乐清照茶府春节不打烊', cluster: 'X', mustRead: false, layerId: null },
  { title: '牌势随好见好就收', cluster: 'X', mustRead: false, layerId: null },
  { title: '为了涨翻放弃涨翻', cluster: 'X', mustRead: false, layerId: null },
  { title: '说顺也不顺', cluster: 'X', mustRead: false, layerId: null },
  { title: '三局连播好运连连', cluster: 'X', mustRead: false, layerId: null },
  { title: '以人为镜可以明得失', cluster: 'X', mustRead: false, layerId: null },
  { title: '坚定执行平常心', cluster: 'X', mustRead: false, layerId: null },
  { title: '不忘初心方得始终', cluster: 'X', mustRead: false, layerId: null },
  { title: '简单小牌美好小运', cluster: 'X', mustRead: false, layerId: null },
  { title: '开年好运生活顺顺', cluster: 'X', mustRead: false, layerId: null },
  { title: '平平淡淡简单美好', cluster: 'X', mustRead: false, layerId: null },
  { title: '排序不对打啥都是错排序号乱打都对', cluster: 'X', mustRead: false, layerId: null },
  { title: '且进且退进退宜得', cluster: 'X', mustRead: false, layerId: null },
  { title: '神奇的牌神奇的运', cluster: 'X', mustRead: false, layerId: null },
  { title: '看完这期视频我看谁还不会利用机麻福利', cluster: 'X', mustRead: false, layerId: null },
]

/** 按关键词模糊找课（归一化后包含匹配，忽略空格与中文标点差异） */
export function findLessonsByTitle(query: string): XioshiLesson[] {
  const q = normalizeTitle(query.trim().toLowerCase())
  if (!q) return []
  return xiaoshiLessons.filter(l => normalizeTitle(l.title.toLowerCase()).includes(q))
}

/** 某一层的全部课程（X 类恒为空） */
export function lessonsOfLayer(layerId: string): XioshiLesson[] {
  return xiaoshiLessons.filter(l => l.layerId === layerId)
}

/** 课程总数（不含生活互动） */
export const xiaoshiLessonCount = xiaoshiLessons.filter(l => l.layerId !== null).length
