// 破晓哥实战决策库 · 归纳规则库（跨期归纳产物）
// ⚠️ 由 xiaolaoshi/tools/sync_knowledge.py 同步生成，勿手改
// 规则 = trigger(局面) + action(行动) + rationale(金句) + boundary(边界) + evidence(案例证据)
// 约定：单期证据 confidence ≤ 0.85；跨期 ≥3 期复现才可升至 0.9+。
// 定位：训练引擎「导师建议」通道的直接消费对象（风格镜像，非唯一真理）。

import type { DecisionTheme, XiaoshiRule } from './xiaoshiTypes'

export const XIAOSHI_RULES: readonly XiaoshiRule[] = [
  {
    id: 'R-DROP-CALL-v0',
    name: '碰牌下叫前先算叫的存活率',
    trigger: '可碰并可立即下叫，但胡张为中张/邻侧未断张/易被顺子带走',
    action: '不碰，保留变叫空间',
    rationale: '暂时不要叫，是为了后面更好的叫',
    boundary: '碰后叫存活率高则照碰（如三六九条且三条良好）',
    evidence: ['cas_001_d1'],
    confidence: 0.85,
  },
  {
    id: 'R-RIVER-INFER-v0',
    name: '对手弃牌邻张反推其手牌',
    trigger: '需判断对手是否持某门高张',
    action: '查其已打邻张（打过7筒9筒→大概率无567/456筒）',
    rationale: '下家手上极大概率是没有高张筒子的',
    boundary: '对手非常规打法时置信度下调',
    evidence: ['cas_001_d2', 'cas_001_d3'],
    confidence: 0.75,
  },
  {
    id: 'R-THREAT-ESCAPE-v0',
    name: '威胁满牌时点炮就走',
    theme: '防守与逃跑',
    trigger: '有对手大牌成势（如大单调+杠上花路径：断张推断其待杠张必在墙内），自己听牌且对手点炮可胡',
    action: '点炮即胡，不『放一手』等自摸；点炮张越接近满牌路径越必走',
    rationale: '该怂就怂，不然挨个满的；即使下家打出三万我也会胡这个牌，当然如果打出六万就更要走了',
    boundary: '无满牌威胁时保留放一手打法',
    evidence: ['cas_002_d2'],
    confidence: 0.8,
  },
  {
    id: 'R-KEEP-LIVE-v0',
    name: '孤张二选一：用牌河算存活账',
    theme: '对子搭子与牌效率',
    trigger: '碰/杠后需从两张孤张中弃一（均无现搭子）',
    action: '留『存活信息更确定』的张：对手打过其邻张/相关张→更易摸对且安全；被多家要的→难成对先弃',
    rationale: '哪一张多留一下就多一个成对儿的机会',
    boundary: '对手以拆搭（抱肚子）方式打过时推断反转',
    evidence: ['cas_002_d1'],
    confidence: 0.75,
  },
  {
    id: 'R-CHECK-DINGQUE-BEFORE-PONG-v0',
    name: '早期碰牌前先看全缺章',
    theme: '对子搭子与牌效率',
    trigger: '开局早期（定缺刚结束）出现可碰的牌，且尚未确认各家缺章',
    action: '先确认各家缺章再决定是否碰：碰牌不可逆，早碰可能锁死更好的清一色路线',
    rationale: '碰牌之后才知道下家也缺万，结果外面三家缺万，这张二筒就碰亏了，不然这牌肯定是去做万清的',
    boundary: '缺章信息已明确、或碰牌方向与缺章优势一致时可放心碰',
    evidence: ['cas_011_d1'],
    confidence: 0.85,
  },
  {
    id: 'R-BIGDANDIAO-VS-XIAJIAO-v0',
    name: '大单调最大化 vs 下叫优先：算吊张差',
    theme: '找叫与选叫',
    trigger: '可在『先不下叫保留多吊张』与『立即下叫』之间选择',
    action: '分别算两种路线的理论吊张数：差别 ≤1 张 → 选早下叫（即时收益+防守）；差别明显 → 选吊张更多的路线',
    rationale: '由于差别只有一张，我还是选择了先打掉五万，胡卡张八万',
    boundary: '『理论吊张』会随外面摸牌而减少（在碰出关键张之前别人可能摸走吊张），需按当前时点估算',
    evidence: ['cas_011_d2'],
    confidence: 0.85,
  },
  {
    id: 'R-ZIMO-OR-NOTHING-v0',
    name: '自摸就走，点炮不胡',
    theme: '期望与进攻',
    trigger: '听牌后自摸收益远大于点炮收益（如自摸12分 vs 点炮小分），且自己尚未面临紧迫威胁',
    action: '预设：自摸即走；他人点炮则不胡，继续等自摸',
    rationale: '如果摸到八万先自摸三家，收入十二分就胡了；但是如果外面八万点炮，我是不会胡的',
    boundary: '牌局将尽（无自摸机会）或对手满牌威胁成型时，改为点炮就走',
    evidence: ['cas_011_d3', 'cas_003_d4'],
    confidence: 0.85,
  },
  {
    id: 'R-NO-RELY-CROWDED-SUIT-v0',
    name: '四家都要的门别抱指望',
    theme: '找叫与选叫',
    trigger: '某门是四家都要（缺章无优势），手上该门看似张数很多',
    action: '该门的下叫张实际难上，改从他门找下叫路线；不要被『看着很多』误导',
    rationale: '首先筒子是4家要的牌，4筒和1筒肯定都很难上…虽然看着1、4筒还很多，但是靠1、4筒基本上没有指望',
    boundary: '若该门确实已无人争（后续确认），则重新纳入考虑',
    evidence: ['cas_012_d2'],
    confidence: 0.8,
  },
  {
    id: 'R-SIMPLE-ROUTE-FIRST-v0',
    name: '简单稳健路线优先于复杂推断',
    theme: '心态与理念',
    trigger: '需要在一个『多路下叫的简单打法』与一个『依赖深层推断的单点打法』之间选择',
    action: '当简单路线已具备多路上叫且不劣时，优先简单路线；复杂推断只在明显更优时采用',
    rationale: '所以总结起来，其实这样打也不是太对，这一局当时还是应该打8筒，不应该打7万。我这算是想得太多，还是因为想得不够呢',
    boundary: '不是否定深推断——当简单路线明显更差（如胡张已绝）时，深推断仍必要',
    evidence: ['cas_012_d3'],
    confidence: 0.85,
  },
  {
    id: 'R-REBUILD-HAND-FROM-MELDS-v0',
    name: '用副露+弃牌时序重建对手手牌',
    theme: '形势与信息',
    trigger: '对手已有两副以上副露，需判断其手牌结构与剩余张分布',
    action: '副露决定其主门 → 结合其早期弃张做反事实排除（若他有X组合，就不会先打Y）→ 重建结构',
    rationale: '他已经碰了3筒8筒两副筒子，手上应该是万子居多，应该是一坎2万、一对3万；如果是4、5万的话，对家就是1、3、6万的叫，之前他不会打1万出来',
    boundary: '对手打法非常规时降权；重建结果用于估算张数而非精确断言',
    evidence: ['cas_012_d4'],
    confidence: 0.85,
  },
  {
    id: 'R-EV-DECLINE-HU-v0',
    name: '尾盘点炮用 EV 算：放过 vs 胡',
    theme: '期望与进攻',
    trigger: '尾盘（牌墙将尽）被点炮，可胡分值小（如2分），且存在自摸/海底加成机会',
    action: '比较 EV：胡=点炮分（且可能因他人跟张而胡不到）；放过=自摸概率×自摸收益（含海底/加底）。EV 更高者胜；通常放过',
    rationale: '用概率和期望来指导你的打法…期望收益八分，高过胡这张九条的两分',
    boundary: '点炮分很高（大牌）或规则无海底/自摸加成时反转；已是最后一张必须胡则胡',
    evidence: ['cas_003_d4'],
    confidence: 0.85,
  },
  {
    id: 'R-MAX-LIVE-WAIT-v0',
    name: '改叫时选存活张最多的叫口',
    theme: '找叫与选叫',
    trigger: '可在多个叫口间切换（碰/打张改听），各叫口胡张存活数不同',
    action: '选存活张数最多的叫口，不因『已投入的原叫』或单局结果而改口',
    rationale: '九条多一张，永远选九条；我一直是奉行长期主义',
    boundary: '存活数接近时改用进张效率/番型比较；本规则只解决『张数差明显』的情形',
    evidence: ['cas_003_d3'],
    confidence: 0.85,
  },
  {
    id: 'R-SINGLE-LINE-ATTACK-v0',
    name: '缺章优势 → 定进攻方向',
    theme: '期望与进攻',
    trigger: '自己收的门别人都缺（单行道/缺章优势），或反之多人争同一门',
    action: '缺章优势时制定进攻思路：优先把对子腾出来碰/成坎做牌；多人争门时才转追下叫效率',
    rationale: '外面三家缺条，缺章上处于优势，这种时候就适合制定进攻思路',
    boundary: '三家收条（争门）时不打九条追下叫效率的常规在此反转',
    evidence: ['cas_003_d1'],
    confidence: 0.75,
  },
  {
    id: 'R-BIGWAIT-COST-v0',
    name: '做大牌前先算喂牌代价',
    theme: '找叫与选叫',
    trigger: '做大单钓/大牌路线需要拆掉他人争抢的门（如四家都要万却要拆七八九万）',
    action: '放弃大牌路线，改走现成叫口：宁可少番，不放跑肥羊',
    rationale: '如果要做大单钓，可能我还没做成，已经把肥羊都放跑了',
    boundary: '该门无人争抢时大牌路线成立',
    evidence: ['cas_003_d2'],
    confidence: 0.75,
  },
  {
    id: 'R-READ-BIG-DANDIAO-v0',
    name: '从副露+弃张逆推对手单钓范围',
    theme: '形势与信息',
    trigger: '对手碰/杠后做成大单调（单钓），并打出某门的牌；且该门只有少数几家要',
    action: '结合缺章结构（谁能收该门）+ 其历史弃张（打过5万→排除5万相关）锁定其单钓候选张',
    rationale: '他手上只能收住一张万子，打8万，手上无非是掉6万、7万或者9万；而他之前打过5万，所以掉7万和掉9万的机会是最高的',
    boundary: '多家争该门时『只能收住一张』的前提不成立，推断失效',
    evidence: ['cas_004_d1'],
    confidence: 0.85,
  },
  {
    id: 'R-COUNTER-BIG-DANDIAO-v0',
    name: '对付大单调：做大对子满牌压制',
    theme: '期望与进攻',
    trigger: '对手做大单调且其单钓范围已基本锁定',
    action: '放弃单钓型大牌（清七对/青龙七对），改碰出对子走大对子满牌，保持多路叫口，逼其必点',
    rationale: '手上都是活的对子的时候，做大对，就是对付他这种大单调最好的方法',
    boundary: '不为躲对手而降番打张（打4万少一番不划算）；自己的牌本就能做满时才成立',
    evidence: ['cas_004_d2'],
    confidence: 0.85,
  },
  {
    id: 'R-INFO-TWO-COLLECT-v0',
    name: '两家收牌+明确信息≈单行道',
    theme: '形势与信息',
    trigger: '两家对两家的缺章结构，其中一方给出明确信息（副露/弃张模式）',
    action: '视同单行道处理：该门可大胆进攻/做牌',
    rationale: '两家收牌的时候，如果另一方给出了比较明确的信息，那就基本上和单行道一样，有着较大的机会',
    boundary: null,
    evidence: ['cas_004_d4'],
    confidence: 0.6,
  },
  {
    id: 'R-LAW-TWO-NO-WAIT-v0',
    name: '潇式法则第一条：两家不要就下这个叫',
    theme: '找叫与选叫',
    trigger: '能变叫（拆搭/换听）时，存在某门两家都不要（缺章/已明显弃该门）',
    action: '尽量把叫下到两家不要的方向；但按牌面尽力而为，不强行变叫',
    rationale: '两家不要就下这个叫…如果能够变叫，尽量把叫朝着两家不要的方向去下；也要根据牌面尽力为之，而不是强行去下两家不要的叫',
    boundary: '变叫成本高或该门实际胡张很薄（如已被杠断、已现多张、有对手也在收）时不强行变叫；仅当变叫后下叫仍然容易时才无条件执行',
    evidence: ['cas_005_d0', 'cas_005_d2'],
    confidence: 0.85,
  },
  {
    id: 'R-DROP-FUTURE-RISK-v0',
    name: '留久成祸的张要早打',
    theme: '对子搭子与牌效率',
    trigger: '手上某张自己不好上、且被他人（尤其是收该门的对手）摸成对后会让自己被动',
    action: '尽早打出，保留质量更好的搭子方向',
    rationale: '如果三四条存着，待会三条被下家摸成了对，留久了反而成祸患',
    boundary: null,
    evidence: ['cas_005_d1'],
    confidence: 0.75,
  },
  {
    id: 'R-DEPTH-JUDGE-v0',
    name: '用深张/浅张判断哪张先出',
    theme: '形势与信息',
    trigger: '等待某门出张（点炮/碰）时，需判断同门多张中哪张会先出现',
    action: '评估各张的『深度』：深张（无人打、被捏住）不会先出，浅张先出——据此决定保留哪门',
    rationale: '这个牌对于外面一四筒都是深张，一筒很深，反而四筒有可能会出来',
    boundary: '深度判断依赖牌河与对手收门情况，对手行为非常规时降权',
    evidence: ['cas_005_d3'],
    confidence: 0.75,
  },
  {
    id: 'R-PAIR-COUNT-DOWN-v0',
    name: '不做七对时，对子多是负担',
    theme: '对子搭子与牌效率',
    trigger: '手上对子过多（≥3-4 对）且并非走七对/龙七对路线',
    action: '主动拆对，优先保证尽早下叫、躲开外面的大牌',
    rationale: '在不做七对的时候，对子多了并不是一件好事；有时候为了能够尽早下叫、躲过外面的大牌，对子多了还得拆掉',
    boundary: '七对/龙七对路线不适用',
    evidence: ['cas_006_d1'],
    confidence: 0.75,
  },
  {
    id: 'R-CHOOSE-PAIR-TO-BREAK-v0',
    name: '拆对四判据：碰出概率>安全',
    theme: '对子搭子与牌效率',
    trigger: '必须从多对中拆一对',
    action: '① 先锁死『极大概率能碰/能下叫』的对（如邻张已断的中张对）；② 生张边张最容易崩对→优先拆；③ 若对手在做七对，其摸不上来的张早晚会打出→保留该对；④ 不要因为『打某张安全』而拆错对',
    rationale: '虽然九条看着最危险、一张没出，但其实打九条才是最正确的',
    boundary: '安全张≠正确张；判据随对手路线（七对/清一色）而变',
    evidence: ['cas_006_d3'],
    confidence: 0.85,
  },
  {
    id: 'R-HIGH-DEEP-NO-UP-v0',
    name: '高张太深就别指望上高张',
    theme: '对子搭子与牌效率',
    trigger: '需要靠摸高张（如八条）来下叫，但该门高张在桌面极深（无人打、明显被捏）',
    action: '改走低张方向；必要时用弃张做『骗张』诱导他人打出目标张',
    rationale: '桌面上的高张非常的深，估计七八九条都不太好出，所以不太指望去上八条；打掉七条，说不定还可以把九条骗出来',
    boundary: null,
    evidence: ['cas_006_d2'],
    confidence: 0.75,
  },
  {
    id: 'R-NOREACTION-INFO-v0',
    name: '对手『无反应』也是信息',
    theme: '形势与信息',
    trigger: '某家在做某门清一色/大牌，却对打出的该门关键张无反应（不碰不胡）',
    action: '推断该门高张已成结构（两副顺子/对子），并据此修正其路线判断（如七对+清一色）',
    rationale: '在我打了七条、上家打了八条、对家没有反应之后，我就知道高张条子非常容易成了两副顺子',
    boundary: '对手可能只是没听牌，需结合其副露与弃牌模式综合判断',
    evidence: ['cas_006_d4'],
    confidence: 0.8,
  },
  {
    id: 'R-ESCAPE-AVOID-BIG-v0',
    name: '躲大牌优先于做大牌',
    theme: '防守与逃跑',
    trigger: '识别出某家做大牌（连续弃某门/杠该门/副露集中）',
    action: '把目标从『做大自己的牌』切换为『防御逃跑』：优先下叫、优先躲，恰到好处地贪分',
    rationale: '学会躲大牌比做大牌更加重要；平均下来你每做一个大牌，外面三家也各会做一个大牌',
    boundary: '自己大牌已成型且对手威胁可控时不必强行降速',
    evidence: ['cas_007_d1'],
    confidence: 0.8,
  },
  {
    id: 'R-ESCAPE-SWITCH-SUIT-v0',
    name: '对手做清一色 → 反向利用缺章',
    theme: '防守与逃跑',
    trigger: '对手做清一色（收某门、弃另外两门）',
    action: '把自己的叫口换到『他不要的那门』：原本的缺章弱势会反转成两家不要的优势',
    rationale: '对家做清一色，万子都不要，那么原本的缺张弱势就变成了两家不要万',
    boundary: '确认对手确在走清一色才成立；换叫后还需考虑另一家是否也收该门',
    evidence: ['cas_007_d2'],
    confidence: 0.85,
  },
  {
    id: 'R-ENUM-PROB-CHOICE-v0',
    name: '读不准就枚举情形算张数',
    theme: '形势与信息',
    trigger: '对手手牌无法精确推断（如早早听牌、该门一张未打），需在两个叫口间选择',
    action: '枚举对手可能的牌型组合 → 逐情形列出各候选叫口剩余张数 → 加总比较，选期望最大者',
    rationale: '无法算出下家准确的手牌，只能用概率来辅助自己，做出最大可能性的选择',
    boundary: '能精确读牌时用精确解；枚举成本高于收益时（如时间紧）可用简化存活张数估算',
    evidence: ['cas_007_d3'],
    confidence: 0.85,
  },
  {
    id: 'R-SET-BOTTOM-LINE-v0',
    name: '中前期定好走/放底线',
    theme: '防守与逃跑',
    trigger: '听牌后面对可能的点炮，需在『点炮即胡』与『放一手』间抉择',
    action: '提前（中前期）按胡张剩余数、自己做大机会、对手是否已听，设定哪些张必胡、哪些可放；临场坚定执行',
    rationale: '要提前想好自己的底线和原则，然后坚定的执行；现在这牌九筒点炮就胡，六筒看情况',
    boundary: '对手存在满牌/杠上花紧迫威胁时升级为『点炮就走』（见 R-THREAT-ESCAPE-v0）',
    evidence: ['cas_008_d1', 'cas_008_d3'],
    confidence: 0.85,
  },
  {
    id: 'R-NO-ARMS-RACE-v0',
    name: '多家做大时不加入军备竞赛',
    theme: '期望与进攻',
    trigger: '已识别两家及以上在做清一色/大牌，自己也有做大牌的念头',
    action: '放弃自己的大牌路线，转稳健下叫：慢一步就成炮台',
    rationale: '我就不去拼筒子清一色了，除非我能先摸到二筒，这种几率太小',
    boundary: '自己关键张极早到位（起手即接近成型）时可例外',
    evidence: ['cas_008_d2'],
    confidence: 0.75,
  },
  {
    id: 'R-QING-TRAP-v0',
    name: '清一色陷阱：先算必备张存活',
    theme: '期望与进攻',
    trigger: '想做清一色/大牌，需要连摸多张关键张（如『一三六七条全被我摸到』）',
    action: '先算必备关键张的存活情况：已被打绝、绝在自己手、需连摸多张 → 判为『做出来是给大家看的』，果断放弃转稳健',
    rationale: '这个牌做清一色，做出来就是给大家看的，除非外面有人没叫；实战的时候这张一条基本没有考虑',
    boundary: '关键张多数存活且外面确实有人没叫时，清一色仍可成立',
    evidence: ['cas_009_d1'],
    confidence: 0.85,
  },
  {
    id: 'R-FUTURE-WAIT-DEAD-v0',
    name: '未来的叫也要先算存活',
    theme: '形势与信息',
    trigger: '评估一条『先牺牲现在、未来再下叫』的做牌路线',
    action: '预判未来叫口的关键张是否会被对手顺子结构吃掉；若未来叫是死叫，该路线直接排除',
    rationale: '即使后面摸到三六条，胡一四条、一四七条都是死叫，因为上家顺子的情况不管哪一种，四条都是没有的',
    boundary: null,
    evidence: ['cas_009_d2'],
    confidence: 0.8,
  },
  {
    id: 'R-EXPECT-MINDSET-v0',
    name: '期望收益意识：结果不改打法',
    theme: '心态与理念',
    trigger: '某次『按概率/期望做的选择』被单局结果打脸（本可胡更大却错过）',
    action: '坚持原打法，不因单局结果追认或改口；用长期进分衡量',
    rationale: '但是打法上来说，我永远不会这样打…打牌一定要有期望收益意识，这一点非常重要',
    boundary: null,
    evidence: ['cas_009_d3'],
    confidence: 0.85,
  },
  {
    id: 'R-NO-ZHANG-PLAN-v0',
    name: '不上牌时：下叫优先 + 兼顾防守',
    theme: '找叫与选叫',
    trigger: '打不缺、摸不上牌（连续摸到无用张）',
    action: '重估单牌与搭子的取舍，优先提高下叫机会；同时避免让别家轻易坐大',
    rationale: '一定要注意好对单牌和搭子的取舍，尽量的提高下叫的机会，同时也做好防守，不要让别人的牌轻易坐大',
    boundary: null,
    evidence: ['cas_010_d1'],
    confidence: 0.75,
  },
  {
    id: 'R-EARLY-SAFE-DISCARD-v0',
    name: '已被碰过的张：早打早安全',
    theme: '防守与逃跑',
    trigger: '手上某张已被他人碰过（或已杠断），且该张对自己下叫无帮助',
    action: '尽早打出（风险高且无用）；保留仍有潜在价值（可成对/可配合碰出）的张',
    rationale: '上家已经碰过4万，早打早安全；4万对于我们下叫没有任何帮助，但是8万留下有可能摸成一对',
    boundary: '若该张是自己叫口的关键张则另论',
    evidence: ['cas_010_d3'],
    confidence: 0.8,
  },
  {
    id: 'R-INFER-BEFORE-PONG-v0',
    name: '看他『碰之前打过什么』',
    theme: '形势与信息',
    trigger: '需要判断某张是否还在牌墙，而常规断张信息不足',
    action: '检查对手在副露（碰/杠）之前打过什么：用反事实推理——若他真有某组合，他不会那样打',
    rationale: '上家在碰4万之前打过一张2万。如果上家手上有1、2、3万，他完全没必要打2万',
    boundary: '依赖对手打法合理；对手非常规时降权',
    evidence: ['cas_010_d4'],
    confidence: 0.85,
  },
  {
    id: 'R-DROP-DEAD-PAIR-v0',
    name: '死对先打别舍不得',
    theme: '对子搭子与牌效率',
    trigger: '手上存在已成绝张/无价值的对子（死对）',
    action: '早点打掉腾位置，并随时准备因胡张被打绝而换叫',
    rationale: '3条、1万都是死对，先打掉1万；边3万的叫已经被打绝了…改下4条的叫，赶上了最后一张',
    boundary: null,
    evidence: ['cas_010_d5'],
    confidence: 0.8,
  },
] as const

/** 按 id 精确查找规则 */
export function getXiaoshiRule(id: string): XiaoshiRule | undefined {
  return XIAOSHI_RULES.find(r => r.id === id)
}

/** 按主题筛选规则 */
export function getXiaoshiRulesByTheme(theme: DecisionTheme): readonly XiaoshiRule[] {
  return XIAOSHI_RULES.filter(r => r.theme === theme)
}

/** 校验规则证据完整性：evidence 中的案例 id 必须真实存在于决策卡库（供测试与开发期自检） */
export function validateRuleEvidence(caseIds: ReadonlySet<string>): string[] {
  return XIAOSHI_RULES.flatMap(r => r.evidence.filter(id => !caseIds.has(id)))
}
